/* CREATE TABLES */
CREATE TABLE StudyItems 
(   [StudyItemId]         INT    IDENTITY(1,1)   PRIMARY KEY   NOT NULL,
    [Unit]       INT            NOT NULL,
    [German]     VARCHAR (200)  NOT NULL,
    [Chinese]    NVARCHAR (200) NOT NULL,
);

CREATE TABLE Scores 
(   [ScoreId]         INT    IDENTITY(1,1)   PRIMARY KEY   NOT NULL,
    [Unit]       INT            NOT NULL,
    [Score]      FLOAT NOT NULL,
);

CREATE TABLE MyWords
(
    [MyWordId]         INT    IDENTITY(1,1)   PRIMARY KEY   NOT NULL,
    [German]     VARCHAR (200)  NOT NULL UNIQUE,
    [Chinese]    NVARCHAR (200) NOT NULL,
);
/*insert into Scoress*/
INSERT INTO "Scores" VALUES(1,0);
INSERT INTO "Scores" VALUES(2,0);
INSERT INTO "Scores" VALUES(3,0);
INSERT INTO "Scores" VALUES(4,0);
INSERT INTO "Scores" VALUES(5,0);
INSERT INTO "Scores" VALUES(6,0);
INSERT INTO "Scores" VALUES(7,0);
INSERT INTO "Scores" VALUES(8,0);
INSERT INTO "Scores" VALUES(9,0);
INSERT INTO "Scores" VALUES(10,0);
INSERT INTO "Scores" VALUES(11,0);
INSERT INTO "Scores" VALUES(12,0);
INSERT INTO "Scores" VALUES(13,0);
INSERT INTO "Scores" VALUES(14,0);
INSERT INTO "Scores" VALUES(15,0);
INSERT INTO "Scores" VALUES(16,0);
INSERT INTO "Scores" VALUES(17,0);
INSERT INTO "Scores" VALUES(18,0);
INSERT INTO "Scores" VALUES(19,0);
INSERT INTO "Scores" VALUES(20,0);
INSERT INTO "Scores" VALUES(21,0);
INSERT INTO "Scores" VALUES(22,0);
INSERT INTO "Scores" VALUES(23,0);
INSERT INTO "Scores" VALUES(24,0);
INSERT INTO "Scores" VALUES(25,0);
INSERT INTO "Scores" VALUES(26,0);
INSERT INTO "Scores" VALUES(27,0);
INSERT INTO "Scores" VALUES(28,0);
INSERT INTO "Scores" VALUES(29,0);
INSERT INTO "Scores" VALUES(30,0);
INSERT INTO "Scores" VALUES(31,0);
INSERT INTO "Scores" VALUES(32,0);
INSERT INTO "Scores" VALUES(33,0);
INSERT INTO "Scores" VALUES(34,0);
INSERT INTO "Scores" VALUES(35,0);
INSERT INTO "Scores" VALUES(36,0);
INSERT INTO "Scores" VALUES(37,0);
INSERT INTO "Scores" VALUES(38,0);
INSERT INTO "Scores" VALUES(39,0);
INSERT INTO "Scores" VALUES(40,0);
INSERT INTO "Scores" VALUES(41,0);
INSERT INTO "Scores" VALUES(42,0);
INSERT INTO "Scores" VALUES(43,0);
INSERT INTO "Scores" VALUES(44,0);
INSERT INTO "Scores" VALUES(45,0);
INSERT INTO "Scores" VALUES(46,0);
INSERT INTO "Scores" VALUES(47,0);
INSERT INTO "Scores" VALUES(48,0);
INSERT INTO "Scores" VALUES(49,0);
INSERT INTO "Scores" VALUES(50,0);
INSERT INTO "Scores" VALUES(51,0);
INSERT INTO "Scores" VALUES(52,0);
INSERT INTO "Scores" VALUES(53,0);
INSERT INTO "Scores" VALUES(54,0);
INSERT INTO "Scores" VALUES(55,0);
INSERT INTO "Scores" VALUES(56,0);
INSERT INTO "Scores" VALUES(57,0);
INSERT INTO "Scores" VALUES(58,0);
INSERT INTO "Scores" VALUES(59,0);
INSERT INTO "Scores" VALUES(60,0);
INSERT INTO "Scores" VALUES(61,0);
INSERT INTO "Scores" VALUES(62,0);
INSERT INTO "Scores" VALUES(63,0);
INSERT INTO "Scores" VALUES(64,0);
INSERT INTO "Scores" VALUES(65,0);
INSERT INTO "Scores" VALUES(66,0);
INSERT INTO "Scores" VALUES(67,0);
INSERT INTO "Scores" VALUES(68,0);
INSERT INTO "Scores" VALUES(69,0);
INSERT INTO "Scores" VALUES(70,0);



/*insert into StudyItems*/
INSERT INTO "StudyItems" VALUES(3,'das Gulasch, -s / -e', N'辣味红烧牛肉');
INSERT INTO "StudyItems" VALUES(4,'das Amt,   ^er', N'局；职务');
INSERT INTO "StudyItems" VALUES(5,'das Angebot, -e', N'供应，提供');
INSERT INTO "StudyItems" VALUES(6,'das Ansehen', N'威望，声望');
INSERT INTO "StudyItems" VALUES(7,'das Appartement,   -s (App.)', N'套间，公寓');
INSERT INTO "StudyItems" VALUES(8,'das Arbeitszimmer,   -', N'工作室  ');
INSERT INTO "StudyItems" VALUES(9,'das Argument, -e', N'论点，论据');
INSERT INTO "StudyItems" VALUES(10,'das Auge,   -n', N'眼睛');
INSERT INTO "StudyItems" VALUES(11,'das Ausland', N'外国');
INSERT INTO "StudyItems" VALUES(12,'das Auslandsamt,   ^er', N'留学生事务办公室');
INSERT INTO "StudyItems" VALUES(13,'das Auto, -s', N'小汽车');
INSERT INTO "StudyItems" VALUES(14,'das Baby, -s', N'婴儿');
INSERT INTO "StudyItems" VALUES(15,'das Bauingenieurwesen', N'土木工程学');
INSERT INTO "StudyItems" VALUES(16,'das Bauwerk, -e', N'(艺术性较高的)建筑物');
INSERT INTO "StudyItems" VALUES(17,'das Bein,   -e', N'腿');
INSERT INTO "StudyItems" VALUES(18,'das Bett,   -en', N'床');
INSERT INTO "StudyItems" VALUES(19,'das Bewußtsein', N'意识，觉悟');
INSERT INTO "StudyItems" VALUES(20,'das Bier', N'啤酒');
INSERT INTO "StudyItems" VALUES(21,'das Blut', N'血液');
INSERT INTO "StudyItems" VALUES(22,'das Boot,   -e', N'木船');
INSERT INTO "StudyItems" VALUES(23,'das Brathähnchen, -', N'烤鸡');
INSERT INTO "StudyItems" VALUES(24,'das Briefpapier', N'信纸');
INSERT INTO "StudyItems" VALUES(25,'das Brot, -e', N'面包');
INSERT INTO "StudyItems" VALUES(26,'das Buch, ^er', N'书');
INSERT INTO "StudyItems" VALUES(27,'das Bücherregal,   -e', N'书橱');
INSERT INTO "StudyItems" VALUES(28,'das Bühnenbild, -er', N'舞台布景');
INSERT INTO "StudyItems" VALUES(29,'das Bundesland, ^er', N'联邦州');
INSERT INTO "StudyItems" VALUES(30,'das Bündnis,   -se', N'联盟；同盟');
INSERT INTO "StudyItems" VALUES(31,'das Cafe, -s', N'咖啡馆');
INSERT INTO "StudyItems" VALUES(32,'das Chinesisch', N'汉语');
INSERT INTO "StudyItems" VALUES(33,'das Datennetz, -e', N'数据网');
INSERT INTO "StudyItems" VALUES(34,'das Detail,   -s', N'细节；详细');
INSERT INTO "StudyItems" VALUES(35,'das Deutsch', N'德语');
INSERT INTO "StudyItems" VALUES(36,'das Ding, -e', N'物，东西，事情');
INSERT INTO "StudyItems" VALUES(37,'das Diplom,   -e', N'证书；(大学)毕业文凭');
INSERT INTO "StudyItems" VALUES(38,'das Dorf,   ^er', N'村庄');
INSERT INTO "StudyItems" VALUES(39,'das Dorf, ^er', N'乡村；村庄');
INSERT INTO "StudyItems" VALUES(40,'das Ehepaar,   -e', N'夫妻');
INSERT INTO "StudyItems" VALUES(41,'das Ei, -er', N'蛋');
INSERT INTO "StudyItems" VALUES(42,'das Einkommen', N'收入');
INSERT INTO "StudyItems" VALUES(43,'das Eis', N'冰块；冰淇淋');
INSERT INTO "StudyItems" VALUES(44,'das Eisbein, -e', N'白煮腌猪蹄');
INSERT INTO "StudyItems" VALUES(45,'das Eiweiß,   -e', N'蛋白');
INSERT INTO "StudyItems" VALUES(46,'das Elektroauto,   -s', N'电子汽车');
INSERT INTO "StudyItems" VALUES(47,'das Elternhaus, ^er', N'家庭');
INSERT INTO "StudyItems" VALUES(48,'das Ende, -n', N'结束；终点');
INSERT INTO "StudyItems" VALUES(49,'das Englisch', N'英语');
INSERT INTO "StudyItems" VALUES(50,'das Enkelkind, -er', N'(外)孙子女');
INSERT INTO "StudyItems" VALUES(51,'das Entwicklungsland,   ^er', N'发展中国家');
INSERT INTO "StudyItems" VALUES(52,'das Erdbeben, -', N'地震');
INSERT INTO "StudyItems" VALUES(53,'das Ereignis,   -se', N'事件');
INSERT INTO "StudyItems" VALUES(54,'das Ergebnis, -se', N'结果');
INSERT INTO "StudyItems" VALUES(55,'das Erlebnis,   -se', N'经历');
INSERT INTO "StudyItems" VALUES(56,'das Eßstäbchen, -', N'筷子');
INSERT INTO "StudyItems" VALUES(57,'das Exemplar,   -e', N'样本；份');
INSERT INTO "StudyItems" VALUES(58,'das Fahrrad, ^er', N'自行车');
INSERT INTO "StudyItems" VALUES(59,'das Fahrzeug, -e', N'交通工具');
INSERT INTO "StudyItems" VALUES(60,'das Fax, -e', N'传真');
INSERT INTO "StudyItems" VALUES(61,'das Feld, -er', N'田地，农田');
INSERT INTO "StudyItems" VALUES(62,'das Fell,   -e', N'兽皮');
INSERT INTO "StudyItems" VALUES(63,'das Fenster, -', N'窗户');
INSERT INTO "StudyItems" VALUES(64,'das Finale, -', N'决赛');
INSERT INTO "StudyItems" VALUES(65,'das Finanzzentrum,   ...tren', N'金融中心');
INSERT INTO "StudyItems" VALUES(66,'das Fleisch', N'肉');
INSERT INTO "StudyItems" VALUES(67,'das Flugzeug, -e', N'飞机');
INSERT INTO "StudyItems" VALUES(68,'das Foto, -s', N'照片');
INSERT INTO "StudyItems" VALUES(69,'das Fotoalbum, ...ben', N'相册');
INSERT INTO "StudyItems" VALUES(70,'das Französisch', N'法语');
INSERT INTO "StudyItems" VALUES(1,'das Frühlingsfest', N'春节');
INSERT INTO "StudyItems" VALUES(2,'das Funkgerät, -e', N'无线电收发机');
INSERT INTO "StudyItems" VALUES(3,'das Gebäude, -', N'大楼');
INSERT INTO "StudyItems" VALUES(4,'das Gebäude, -', N'高楼，大厦');
INSERT INTO "StudyItems" VALUES(5,'das Gebiet, -e', N'领域');
INSERT INTO "StudyItems" VALUES(6,'das Gebirge, -', N'山脉');
INSERT INTO "StudyItems" VALUES(7,'das Geburtsdatum, ...ten', N'出生日期');
INSERT INTO "StudyItems" VALUES(8,'das Gedicht, -e', N'诗');
INSERT INTO "StudyItems" VALUES(9,'das Gefängnis,  -se', N'监狱');
INSERT INTO "StudyItems" VALUES(10,'das Geflügel, -', N'家禽');
INSERT INTO "StudyItems" VALUES(11,'das Gegenteil, -e', N'相反');
INSERT INTO "StudyItems" VALUES(12,'das Gehalt, ^er', N'薪金');
INSERT INTO "StudyItems" VALUES(13,'das Gehalt, ^er', N'薪金');
INSERT INTO "StudyItems" VALUES(14,'das Geld', N'钱');
INSERT INTO "StudyItems" VALUES(15,'das Geldstück, -e', N'硬币');
INSERT INTO "StudyItems" VALUES(16,'das Gemüse', N'蔬菜');
INSERT INTO "StudyItems" VALUES(17,'das Genußmittel, -', N'奢用品');
INSERT INTO "StudyItems" VALUES(18,'das Gericht, -e', N'一道(菜)');
INSERT INTO "StudyItems" VALUES(19,'das Gerücht,   -e', N'谣言；传闻');
INSERT INTO "StudyItems" VALUES(20,'das Geschenk, -e', N'礼物');
INSERT INTO "StudyItems" VALUES(21,'das Gesicht,   -er', N'脸庞');
INSERT INTO "StudyItems" VALUES(22,'das Getränk,   -e', N'饮料');
INSERT INTO "StudyItems" VALUES(23,'das Getreide', N'粮食');
INSERT INTO "StudyItems" VALUES(24,'das Girokonto, ...ten', N'汇计帐户');
INSERT INTO "StudyItems" VALUES(25,'das Glas,^er', N'杯，杯子');
INSERT INTO "StudyItems" VALUES(26,'das Glutamat', N'味精');
INSERT INTO "StudyItems" VALUES(27,'das Gold', N'金子');
INSERT INTO "StudyItems" VALUES(28,'das Gramm', N'克');
INSERT INTO "StudyItems" VALUES(29,'das Haar, -e', N'头发');
INSERT INTO "StudyItems" VALUES(30,'das Hähnchen, -', N'童子鸡');
INSERT INTO "StudyItems" VALUES(31,'das Haushaltsgerät,   -e', N'家电');
INSERT INTO "StudyItems" VALUES(32,'das Haushaltsmittel, -', N'家用品');
INSERT INTO "StudyItems" VALUES(33,'das Heft, -e', N'本子，练习本');
INSERT INTO "StudyItems" VALUES(34,'das Heilige Römische Reich Deutscher Nation', N'德意志民族神圣罗马帝国');
INSERT INTO "StudyItems" VALUES(35,'das Heimweh', N'想家');
INSERT INTO "StudyItems" VALUES(36,'das Hemd,   -en', N'男衬衫');
INSERT INTO "StudyItems" VALUES(37,'das Herz, -ens, -en', N'心');
INSERT INTO "StudyItems" VALUES(38,'das Hobby, -s', N'爱好');
INSERT INTO "StudyItems" VALUES(39,'das Hofhaus, ^er', N'四合院');
INSERT INTO "StudyItems" VALUES(40,'das Hofkonzert, -e', N'宫廷音乐');
INSERT INTO "StudyItems" VALUES(41,'das Hörverständnis', N'听力');
INSERT INTO "StudyItems" VALUES(42,'das Huhn, ^er', N'鸡');
INSERT INTO "StudyItems" VALUES(43,'das Hühnlein, -', N'小鸡');
INSERT INTO "StudyItems" VALUES(44,'das Inland', N'本国；内地');
INSERT INTO "StudyItems" VALUES(45,'das Instrument, -e', N'乐器');
INSERT INTO "StudyItems" VALUES(46,'das Internet', N'互联网');
INSERT INTO "StudyItems" VALUES(47,'das Jahrhundert, -e', N'世纪');
INSERT INTO "StudyItems" VALUES(48,'das Jahrhundert, -e', N'世纪');
INSERT INTO "StudyItems" VALUES(49,'das Jahrzehnt, -e', N'十年');
INSERT INTO "StudyItems" VALUES(50,'das Japanisch', N'日语');
INSERT INTO "StudyItems" VALUES(51,'das Kännchen, -', N'小茶壶');
INSERT INTO "StudyItems" VALUES(52,'das Kaufhaus, ^er', N'商店');
INSERT INTO "StudyItems" VALUES(53,'das Kilo', N'公斤');
INSERT INTO "StudyItems" VALUES(54,'das Kind, -er', N'孩子');
INSERT INTO "StudyItems" VALUES(55,'das Kinderheim, -e', N'儿童之家');
INSERT INTO "StudyItems" VALUES(56,'das Kinderzimmer, -', N'儿童房间');
INSERT INTO "StudyItems" VALUES(57,'das Kino, -s', N'电影院');
INSERT INTO "StudyItems" VALUES(58,'das Klassenzimmer, -', N'教室');
INSERT INTO "StudyItems" VALUES(59,'das Klavier,-e', N'钢琴');
INSERT INTO "StudyItems" VALUES(60,'das Kleid, -er', N'连衣裙');
INSERT INTO "StudyItems" VALUES(61,'das Klima,    -s', N'气候');
INSERT INTO "StudyItems" VALUES(62,'das Knie, -', N'膝盖');
INSERT INTO "StudyItems" VALUES(63,'das Kohlenhydrat,   -e', N'碳水化合物');
INSERT INTO "StudyItems" VALUES(64,'das Konto, ...ten', N'帐号；帐户');
INSERT INTO "StudyItems" VALUES(65,'das Konzert, -e', N'音乐会');
INSERT INTO "StudyItems" VALUES(66,'das Koreanisch', N'朝鲜语');
INSERT INTO "StudyItems" VALUES(67,'das Korn, ^er', N'谷粒；种子');
INSERT INTO "StudyItems" VALUES(68,'das Kostüm, -e', N'时装');
INSERT INTO "StudyItems" VALUES(69,'das Kostüm, -e', N'戏装，行头');
INSERT INTO "StudyItems" VALUES(70,'das Kraftwerk, -e', N'发电厂');
INSERT INTO "StudyItems" VALUES(1,'das Kriegsspiel, -e', N'战争游戏');
INSERT INTO "StudyItems" VALUES(2,'das Labor, -s', N'实验室');
INSERT INTO "StudyItems" VALUES(3,'das Lammfleisch', N'羊肉');
INSERT INTO "StudyItems" VALUES(4,'das Land, ^er', N'国家');
INSERT INTO "StudyItems" VALUES(5,'das Land, ^er', N'农村，国家，州');
INSERT INTO "StudyItems" VALUES(6,'das Länderspiel, -e', N'国际比赛');
INSERT INTO "StudyItems" VALUES(7,'das Lehrbuch, ^er', N'教科书');
INSERT INTO "StudyItems" VALUES(8,'das Lied,   -er', N'歌曲');
INSERT INTO "StudyItems" VALUES(9,'das Mädchen, -', N'女孩');
INSERT INTO "StudyItems" VALUES(10,'das Märchen,   -', N'童话');
INSERT INTO "StudyItems" VALUES(11,'das Massenmedium,   ...ien', N'大众传媒');
INSERT INTO "StudyItems" VALUES(12,'das Maul, ^er', N'(兽)嘴');
INSERT INTO "StudyItems" VALUES(13,'das Mauseloch, ^er', N'鼠洞');
INSERT INTO "StudyItems" VALUES(14,'das Mausoleum, ...leen', N'陵墓；纪念堂');
INSERT INTO "StudyItems" VALUES(15,'das Meer, -e', N'洋；海');
INSERT INTO "StudyItems" VALUES(16,'das Meisterwerk, -e', N'杰作');
INSERT INTO "StudyItems" VALUES(17,'das Milchprodukt, -e', N'奶制品');
INSERT INTO "StudyItems" VALUES(18,'das Mineralwasser', N'矿泉水');
INSERT INTO "StudyItems" VALUES(19,'das Mitglied, -er', N'成员');
INSERT INTO "StudyItems" VALUES(20,'das Möbel,   -', N'家具');
INSERT INTO "StudyItems" VALUES(21,'das Mondfest', N'中秋节');
INSERT INTO "StudyItems" VALUES(22,'das Mountain Bike, -s', N'山地车');
INSERT INTO "StudyItems" VALUES(23,'das Museum, ...seen', N'博物馆');
INSERT INTO "StudyItems" VALUES(24,'das Muster,   -', N'图案，花样');
INSERT INTO "StudyItems" VALUES(25,'das nächste Mal', N'下一次');
INSERT INTO "StudyItems" VALUES(26,'das Naturgesetz,   -e', N'自然规律');
INSERT INTO "StudyItems" VALUES(27,'das Neujahr', N'元旦');
INSERT INTO "StudyItems" VALUES(28,'das Oberwasser', N'优势');
INSERT INTO "StudyItems" VALUES(29,'das Obst', N'水果');
INSERT INTO "StudyItems" VALUES(30,'das Ohr,   -en', N'耳朵');
INSERT INTO "StudyItems" VALUES(31,'das Öl', N'油');
INSERT INTO "StudyItems" VALUES(32,'das Paar, -e', N'双，对，付');
INSERT INTO "StudyItems" VALUES(33,'das Päckchen, -', N'小邮包');
INSERT INTO "StudyItems" VALUES(34,'das Paket, -e', N'包裹');
INSERT INTO "StudyItems" VALUES(35,'das Paßfoto, -s', N'证件照');
INSERT INTO "StudyItems" VALUES(36,'das Pech', N'倒霉（口）');
INSERT INTO "StudyItems" VALUES(37,'das Pferd, -e', N'马');
INSERT INTO "StudyItems" VALUES(38,'das Pfund, -e', N'磅');
INSERT INTO "StudyItems" VALUES(39,'das Picknick,   -e / -s', N'野餐');
INSERT INTO "StudyItems" VALUES(40,'das Podium,   ...dien', N'讲台；戏台');
INSERT INTO "StudyItems" VALUES(41,'das Polo-Shirt, -s', N'翻领T恤衫');
INSERT INTO "StudyItems" VALUES(42,'das Polymer, -e', N'(化)聚合物');
INSERT INTO "StudyItems" VALUES(43,'das Porzellan', N'瓷器');
INSERT INTO "StudyItems" VALUES(44,'das Postamt, ^er', N'邮局');
INSERT INTO "StudyItems" VALUES(45,'das Problem, -e', N'问题');
INSERT INTO "StudyItems" VALUES(46,'das Produkt, -e', N'产品');
INSERT INTO "StudyItems" VALUES(47,'das Produkt, -e', N'产品');
INSERT INTO "StudyItems" VALUES(48,'das Prozent, -e', N'百分比');
INSERT INTO "StudyItems" VALUES(49,'das Radio, -s', N'收音机');
INSERT INTO "StudyItems" VALUES(50,'das Rathaus, ^er', N'市政厅');
INSERT INTO "StudyItems" VALUES(51,'das Rätsel, -', N'谜语');
INSERT INTO "StudyItems" VALUES(52,'das Recht, -e', N'权力');
INSERT INTO "StudyItems" VALUES(53,'das Reich,    -e', N'帝国');
INSERT INTO "StudyItems" VALUES(54,'das Reich, -e', N'王国');
INSERT INTO "StudyItems" VALUES(55,'das Reisebüro,   -s', N'旅行社');
INSERT INTO "StudyItems" VALUES(56,'das Reiseziel, -e', N'旅行目的地');
INSERT INTO "StudyItems" VALUES(57,'das Requisit,  -en', N'(戏剧用的)道具');
INSERT INTO "StudyItems" VALUES(58,'das Restaurant, -s', N'饭店');
INSERT INTO "StudyItems" VALUES(59,'das Rezept,   -e', N'药方');
INSERT INTO "StudyItems" VALUES(60,'das Rezept, -e', N'菜谱');
INSERT INTO "StudyItems" VALUES(61,'das Rindfleisch', N'牛肉');
INSERT INTO "StudyItems" VALUES(62,'das Rollbild, -er', N'轴画');
INSERT INTO "StudyItems" VALUES(63,'das Römische Reich', N'罗马帝国');
INSERT INTO "StudyItems" VALUES(64,'das Rotkäppchen', N'小红帽');
INSERT INTO "StudyItems" VALUES(65,'das Rotkraut', N'红(球)甘蓝');
INSERT INTO "StudyItems" VALUES(66,'das Sakko, -s', N'单件西装，便装');
INSERT INTO "StudyItems" VALUES(67,'das Salz', N'盐');
INSERT INTO "StudyItems" VALUES(68,'das Schaf, -e', N'绵羊');
INSERT INTO "StudyItems" VALUES(69,'das Schaukelpferd,   -e', N'摇摆木马');
INSERT INTO "StudyItems" VALUES(70,'das Schiff, -e', N'轮船');
INSERT INTO "StudyItems" VALUES(1,'das Schlafzimmer,   -', N'卧室');
INSERT INTO "StudyItems" VALUES(2,'das Schloß, ^sser', N'城堡');
INSERT INTO "StudyItems" VALUES(3,'das Schlüsselwort, ^er', N'关键词');
INSERT INTO "StudyItems" VALUES(4,'das Schwein, -e', N'猪');
INSERT INTO "StudyItems" VALUES(5,'das Schweinefleisch', N'猪肉');
INSERT INTO "StudyItems" VALUES(6,'das Schwert, -er', N'剑');
INSERT INTO "StudyItems" VALUES(7,'das Schwimmbecken, -', N'游泳池');
INSERT INTO "StudyItems" VALUES(8,'das Segelschiff, -e', N'帆船');
INSERT INTO "StudyItems" VALUES(9,'das Seidentuch, ^er', N'丝巾');
INSERT INTO "StudyItems" VALUES(10,'das Semester, -', N'学期');
INSERT INTO "StudyItems" VALUES(11,'das Seminar, -e', N'(专题)研究班，课堂讨论');
INSERT INTO "StudyItems" VALUES(12,'das Sesamöl, -e', N'香油');
INSERT INTO "StudyItems" VALUES(13,'das Shampoon, -s', N'香波，洗发露');
INSERT INTO "StudyItems" VALUES(14,'das Signal,   -e', N'信号');
INSERT INTO "StudyItems" VALUES(15,'das Silber', N'白银');
INSERT INTO "StudyItems" VALUES(16,'das Silberschiffchen, -', N'银元宝');
INSERT INTO "StudyItems" VALUES(17,'das Sofa,   -s', N'沙发');
INSERT INTO "StudyItems" VALUES(18,'das Sonderangebot, -e', N'特价');
INSERT INTO "StudyItems" VALUES(19,'das Spanisch', N'西班牙语');
INSERT INTO "StudyItems" VALUES(20,'das Sparbuch, ^er', N'储蓄存折');
INSERT INTO "StudyItems" VALUES(21,'das Sparkonto, ...ten', N'存款帐户');
INSERT INTO "StudyItems" VALUES(22,'das Spieglein, -', N'镜子人');
INSERT INTO "StudyItems" VALUES(23,'das Spiel, -e', N'游戏，比赛，赌博');
INSERT INTO "StudyItems" VALUES(24,'das Spielcasino, -s', N'赌场');
INSERT INTO "StudyItems" VALUES(25,'das Stadion, ...ien', N'体育场馆');
INSERT INTO "StudyItems" VALUES(26,'das Stadtzentrum', N'市中心');
INSERT INTO "StudyItems" VALUES(27,'das Stipendium,   ...dien', N'奖学金');
INSERT INTO "StudyItems" VALUES(28,'das Stipendium, ... Dien', N'奖学金');
INSERT INTO "StudyItems" VALUES(29,'das Stofftier, -e', N'绒毛(玩具)动物');
INSERT INTO "StudyItems" VALUES(30,'das Stück, -e', N'(一)块；(一)只');
INSERT INTO "StudyItems" VALUES(31,'das Stück, -e', N'戏剧');
INSERT INTO "StudyItems" VALUES(32,'das Stück, -e', N'乐曲');
INSERT INTO "StudyItems" VALUES(33,'das Studentenwohnheim,   -e', N'学生公寓');
INSERT INTO "StudyItems" VALUES(34,'das Studienfach,   ^er', N'专业');
INSERT INTO "StudyItems" VALUES(35,'das Symbol, -e', N'象征');
INSERT INTO "StudyItems" VALUES(36,'das Symphornieorchester, -', N'交响乐团');
INSERT INTO "StudyItems" VALUES(37,'das Synonym, -e', N'同意词');
INSERT INTO "StudyItems" VALUES(38,'das System, -e', N'体系，制度');
INSERT INTO "StudyItems" VALUES(39,'das Tagebuch, ^er', N'日记');
INSERT INTO "StudyItems" VALUES(40,'das Taschengeld', N'零花钱');
INSERT INTO "StudyItems" VALUES(41,'das Taxi, -s', N'出租车');
INSERT INTO "StudyItems" VALUES(42,'das Teehaus,   ^er', N'茶馆');
INSERT INTO "StudyItems" VALUES(43,'das Telefon, -e', N'电话机');
INSERT INTO "StudyItems" VALUES(44,'das Telegramm, -e', N'电报');
INSERT INTO "StudyItems" VALUES(45,'das Thai', N'泰语');
INSERT INTO "StudyItems" VALUES(46,'das Theater, -', N'剧场');
INSERT INTO "StudyItems" VALUES(47,'das Thema, ...men', N'题目');
INSERT INTO "StudyItems" VALUES(48,'das Tier, -e', N'动物');
INSERT INTO "StudyItems" VALUES(49,'das Tor, -e', N'大门');
INSERT INTO "StudyItems" VALUES(50,'das Training', N'训练');
INSERT INTO "StudyItems" VALUES(51,'das Treibhaus,   ^er', N'温室，暖房');
INSERT INTO "StudyItems" VALUES(52,'das Trinkgeld', N'小费');
INSERT INTO "StudyItems" VALUES(53,'das T-Shirt,   -s', N'圆领T恤衫');
INSERT INTO "StudyItems" VALUES(54,'das Turnier, -e', N'体育比赛');
INSERT INTO "StudyItems" VALUES(55,'das Umbuchen', N'把……过帐，把…转入另帐');
INSERT INTO "StudyItems" VALUES(56,'das Unicafe, -s', N'大学咖啡馆');
INSERT INTO "StudyItems" VALUES(57,'das Unternehmen,    -', N'企业');
INSERT INTO "StudyItems" VALUES(58,'das Verhalten', N'举止，行为');
INSERT INTO "StudyItems" VALUES(59,'das Verhalten', N'举止，行为');
INSERT INTO "StudyItems" VALUES(60,'das Verhältnis,   -se', N'关系');
INSERT INTO "StudyItems" VALUES(61,'das Verkehrsmittel, -', N'交通工具');
INSERT INTO "StudyItems" VALUES(62,'das Verkehrszeichen, -', N'交通标志');
INSERT INTO "StudyItems" VALUES(63,'das Viertel, -', N'一刻，四分之一');
INSERT INTO "StudyItems" VALUES(64,'das Visum, ...sa', N'签证');
INSERT INTO "StudyItems" VALUES(65,'das Volk,   ^er', N'民族；人民');
INSERT INTO "StudyItems" VALUES(66,'das Vorbild, -er', N'榜样');
INSERT INTO "StudyItems" VALUES(67,'das Wachstum', N'增长');
INSERT INTO "StudyItems" VALUES(68,'das Waschpulver, -', N'洗衣粉');
INSERT INTO "StudyItems" VALUES(69,'das Wasser', N'水');
INSERT INTO "StudyItems" VALUES(70,'das WC, -s', N'厕所  ');
INSERT INTO "StudyItems" VALUES(1,'das Weihnachtsgeschenk, -e', N'圣诞礼物');
INSERT INTO "StudyItems" VALUES(2,'das Werk, -e', N'作品');
INSERT INTO "StudyItems" VALUES(3,'das Wetter', N'天气');
INSERT INTO "StudyItems" VALUES(4,'das Wochenende, -n', N'周末');
INSERT INTO "StudyItems" VALUES(5,'das Wohnzimmer, -', N'起居室');
INSERT INTO "StudyItems" VALUES(6,'das Wörterbuch,   ^er', N'词典');
INSERT INTO "StudyItems" VALUES(7,'das Wunder, -', N'奇迹');
INSERT INTO "StudyItems" VALUES(8,'das Wunderkind, -er', N'神童');
INSERT INTO "StudyItems" VALUES(9,'das Zeitalter, -', N'时期；年代');
INSERT INTO "StudyItems" VALUES(10,'das Zelt,   -e', N'帐篷');
INSERT INTO "StudyItems" VALUES(11,'das Zentrum, ...ren', N'中心');
INSERT INTO "StudyItems" VALUES(12,'das Ziel, -e', N'目标，目的地');
INSERT INTO "StudyItems" VALUES(13,'daß Konj.', N'(主从复合句连词)');
INSERT INTO "StudyItems" VALUES(14,'dau ern (es dauert)   Vi.', N'持续');
INSERT INTO "StudyItems" VALUES(15,'dei n Pron.', N'你的');
INSERT INTO "StudyItems" VALUES(16,'den Bus nehmen', N'乘公共汽车');
INSERT INTO "StudyItems" VALUES(17,'den ken (du denkst, er denkt) Vi.', N'想');
INSERT INTO "StudyItems" VALUES(18,'der Abend, -e', N'傍晚，晚上');
INSERT INTO "StudyItems" VALUES(19,'der Abiturient,   -en, -en', N'中学毕业生');
INSERT INTO "StudyItems" VALUES(20,'der Abschied, -e', N'告别');
INSERT INTO "StudyItems" VALUES(21,'der Abschluß, ^sse', N'结束，结业');
INSERT INTO "StudyItems" VALUES(22,'der Absender, -', N'寄信人');
INSERT INTO "StudyItems" VALUES(23,'der Absolvent,   -en,   -en', N'毕业生');
INSERT INTO "StudyItems" VALUES(24,'der Agrarwissenschaftler, -', N'农学家');
INSERT INTO "StudyItems" VALUES(25,'der Akademiker, -', N'受过大学教育者');
INSERT INTO "StudyItems" VALUES(26,'der Alkohol', N'烈酒');
INSERT INTO "StudyItems" VALUES(27,'der Allgemeinarzt,   ^e', N'常见病医生');
INSERT INTO "StudyItems" VALUES(28,'der Amerikaner, -', N'美国人');
INSERT INTO "StudyItems" VALUES(29,'der Angriff, -e', N'进攻');
INSERT INTO "StudyItems" VALUES(30,'der Anhalter', N'搭车');
INSERT INTO "StudyItems" VALUES(31,'der Antiquitätenladen,  ^', N'古玩店');
INSERT INTO "StudyItems" VALUES(32,'der Anzug, ^e', N'西服');
INSERT INTO "StudyItems" VALUES(33,'der Apfel, ^', N'苹果');
INSERT INTO "StudyItems" VALUES(34,'der Apfelkuchen, -', N'苹果蛋糕');
INSERT INTO "StudyItems" VALUES(35,'der April', N'四月');
INSERT INTO "StudyItems" VALUES(36,'der Arbeiter, -', N'工人');
INSERT INTO "StudyItems" VALUES(37,'der Arbeitgeber, -', N'雇主');
INSERT INTO "StudyItems" VALUES(38,'der Arbeitslose, -n (wie Adj.)', N'失业者');
INSERT INTO "StudyItems" VALUES(39,'der Architekt, -en', N'建筑师');
INSERT INTO "StudyItems" VALUES(40,'der Arm, -e', N'手臂');
INSERT INTO "StudyItems" VALUES(41,'der Arzt,^e', N'医生');
INSERT INTO "StudyItems" VALUES(42,'der Assistent, -en, -en', N'助教；助理员');
INSERT INTO "StudyItems" VALUES(43,'der Auflauf, ^e', N'(酥脆的)烤饼');
INSERT INTO "StudyItems" VALUES(44,'der Aufsatz, ^e', N'作文，文章');
INSERT INTO "StudyItems" VALUES(45,'der Auftrag,   ^e', N'任务；定单');
INSERT INTO "StudyItems" VALUES(46,'der Auftrag, ^e', N'委托，使命');
INSERT INTO "StudyItems" VALUES(47,'der Augenblick, -e', N'片刻，瞬间');
INSERT INTO "StudyItems" VALUES(48,'der August (Aug.)', N'八月');
INSERT INTO "StudyItems" VALUES(49,'der Ausflug, ^e', N'郊游');
INSERT INTO "StudyItems" VALUES(50,'der Ausgleich', N'平衡；弥补');
INSERT INTO "StudyItems" VALUES(51,'der Aushang, ^e', N'招帖，布告');
INSERT INTO "StudyItems" VALUES(52,'der Bäcker, -', N'面包师');
INSERT INTO "StudyItems" VALUES(53,'der Backfisch, -e', N'煎鱼');
INSERT INTO "StudyItems" VALUES(54,'der Bahnhof, ^e', N'火车站');
INSERT INTO "StudyItems" VALUES(55,'der Bahnhofsplatz                 .', N'火车站广场');
INSERT INTO "StudyItems" VALUES(56,'der Balkon, -e', N'阳台');
INSERT INTO "StudyItems" VALUES(57,'der Ball, ^e', N'球');
INSERT INTO "StudyItems" VALUES(58,'der Bambus, -se', N'竹');
INSERT INTO "StudyItems" VALUES(59,'der Bankräuber,   -', N'抢银行的强盗');
INSERT INTO "StudyItems" VALUES(60,'der Banküberfall,   ^e', N'袭击银行');
INSERT INTO "StudyItems" VALUES(61,'der Basketballspieler, -', N'篮球运动员');
INSERT INTO "StudyItems" VALUES(62,'der Bauch, ^e', N'肚子');
INSERT INTO "StudyItems" VALUES(63,'der Bauingenieur,   -e', N'土木工程师');
INSERT INTO "StudyItems" VALUES(64,'der Baum,   ^e', N'树，树木');
INSERT INTO "StudyItems" VALUES(65,'der Baustil,   -e', N'建筑式样；风格');
INSERT INTO "StudyItems" VALUES(66,'der Becher, -', N'杯');
INSERT INTO "StudyItems" VALUES(67,'der Beifall', N'鼓掌');
INSERT INTO "StudyItems" VALUES(68,'der Bereich, -e', N'领域，区域');
INSERT INTO "StudyItems" VALUES(69,'der Berg,    -e', N'山');
INSERT INTO "StudyItems" VALUES(70,'der Bergarbeiter,   -', N'矿工');
INSERT INTO "StudyItems" VALUES(1,'der Beruf, -e', N'职业');
INSERT INTO "StudyItems" VALUES(2,'der Besitzer ,  -', N'拥有者，业主');
INSERT INTO "StudyItems" VALUES(3,'der Besuch, -e', N'访问');
INSERT INTO "StudyItems" VALUES(4,'der Betreuer, -', N'导师');
INSERT INTO "StudyItems" VALUES(5,'der Betrüger, -', N'骗子');
INSERT INTO "StudyItems" VALUES(6,'der Beutel, -', N'袋；包');
INSERT INTO "StudyItems" VALUES(7,'der Bewerber, -', N'(在此)求婚者；申请者');
INSERT INTO "StudyItems" VALUES(8,'der Biologe,   -n', N'生物学家');
INSERT INTO "StudyItems" VALUES(9,'der Bleistift, -e', N'铅笔');
INSERT INTO "StudyItems" VALUES(10,'der Blumenkohl', N'花菜');
INSERT INTO "StudyItems" VALUES(11,'der Blumenstrauß, ^e', N'花束');
INSERT INTO "StudyItems" VALUES(12,'der Bluthochdruck', N'高血压');
INSERT INTO "StudyItems" VALUES(13,'der Bonsai, -s', N'盆景');
INSERT INTO "StudyItems" VALUES(14,'der Brand, ^e', N'燃烧；火灾');
INSERT INTO "StudyItems" VALUES(15,'der Bräutigam, -e', N'新郎');
INSERT INTO "StudyItems" VALUES(16,'der Brief, -e', N'信');
INSERT INTO "StudyItems" VALUES(17,'der Briefmarkensammler, -', N'集邮者');
INSERT INTO "StudyItems" VALUES(18,'der Briefpartner, -', N'信友');
INSERT INTO "StudyItems" VALUES(19,'der Briefumschlag,   ^e', N'信封');
INSERT INTO "StudyItems" VALUES(20,'der Brocken,   -', N'碎块，碎片');
INSERT INTO "StudyItems" VALUES(21,'der Bruder, ^', N'兄弟');
INSERT INTO "StudyItems" VALUES(22,'der Brunnen, -', N'井');
INSERT INTO "StudyItems" VALUES(23,'der Bücherwurm, ^er', N'书迷，书呆子');
INSERT INTO "StudyItems" VALUES(24,'der Bund', N'外滩');
INSERT INTO "StudyItems" VALUES(25,'der Bürgermeister, -', N'市长');
INSERT INTO "StudyItems" VALUES(26,'der Charakter,  -e', N'特点；(这里指)形象');
INSERT INTO "StudyItems" VALUES(27,'der Chinakohl', N'大白菜');
INSERT INTO "StudyItems" VALUES(28,'der China-Laden, ^', N'中国商店');
INSERT INTO "StudyItems" VALUES(29,'der Chinese, -n', N'中国人');
INSERT INTO "StudyItems" VALUES(30,'der Clown, -s', N'小丑');
INSERT INTO "StudyItems" VALUES(31,'der Club, -s', N'俱乐部');
INSERT INTO "StudyItems" VALUES(32,'der Computer, -', N'计算机');
INSERT INTO "StudyItems" VALUES(33,'der Dauerauftrag, ^e', N'长期汇票');
INSERT INTO "StudyItems" VALUES(34,'der Deutsche Fußball-Bund (DFB)', N'德国足协');
INSERT INTO "StudyItems" VALUES(35,'der Deutsche, -n', N'德国人');
INSERT INTO "StudyItems" VALUES(36,'der Deutschlehrer, -', N'德语教师');
INSERT INTO "StudyItems" VALUES(37,'der Dezember (Dez.)', N'十二月');
INSERT INTO "StudyItems" VALUES(38,'der Dialog, -e', N'对话');
INSERT INTO "StudyItems" VALUES(39,'der Dichter, -', N'诗人');
INSERT INTO "StudyItems" VALUES(40,'der Dolmetscher, -', N'(口头)翻译');
INSERT INTO "StudyItems" VALUES(41,'der Dom, -e', N'大教堂');
INSERT INTO "StudyItems" VALUES(42,'der Donnerstag, -e', N'星期四');
INSERT INTO "StudyItems" VALUES(43,'der Doufu(Tofu)', N'豆腐');
INSERT INTO "StudyItems" VALUES(44,'der Drache, -n', N'龙');
INSERT INTO "StudyItems" VALUES(45,'der Drache, -n                           .', N'龙');
INSERT INTO "StudyItems" VALUES(46,'der Durchfall, ^e', N'腹泻');
INSERT INTO "StudyItems" VALUES(47,'der Durst', N'口渴');
INSERT INTO "StudyItems" VALUES(48,'der Ehemann, ^er', N'丈夫');
INSERT INTO "StudyItems" VALUES(49,'der Einflug,   ^e', N'入侵');
INSERT INTO "StudyItems" VALUES(50,'der Einfluß,   ^sse', N'影响');
INSERT INTO "StudyItems" VALUES(51,'der Eintopf, ^e', N'大杂烩');
INSERT INTO "StudyItems" VALUES(52,'der Eintritt, -e', N'入场');
INSERT INTO "StudyItems" VALUES(53,'der Einwohner, -', N'居民');
INSERT INTO "StudyItems" VALUES(54,'der Einzelunterricht', N'单独授课');
INSERT INTO "StudyItems" VALUES(55,'der Empfänger, -', N'收信人；接待人员');
INSERT INTO "StudyItems" VALUES(56,'der Engländer, -', N'英国人');
INSERT INTO "StudyItems" VALUES(57,'der Englischkurs, -e', N'英语班');
INSERT INTO "StudyItems" VALUES(58,'der Enkel, -', N'孙子；外孙');
INSERT INTO "StudyItems" VALUES(59,'der Entwerter, -', N'检票箱');
INSERT INTO "StudyItems" VALUES(60,'der Erdbeer-Shake, -s', N'草莓奶昔');
INSERT INTO "StudyItems" VALUES(61,'der Erfolg, -e', N'成就；成果');
INSERT INTO "StudyItems" VALUES(62,'der Ernährer, -', N'抚养者');
INSERT INTO "StudyItems" VALUES(63,'der Erste Weltkrieg', N'第一次世界大战');
INSERT INTO "StudyItems" VALUES(64,'der Erwachsene, -n   (wie Adj.)', N'成年人');
INSERT INTO "StudyItems" VALUES(65,'der Erwachsene, -n   (wie Adj.)', N'成人');
INSERT INTO "StudyItems" VALUES(66,'der Esel, -', N'驴子');
INSERT INTO "StudyItems" VALUES(67,'der Essig,   -e', N'醋');
INSERT INTO "StudyItems" VALUES(68,'der eurocheque, -s', N'欧洲旅行支票');
INSERT INTO "StudyItems" VALUES(69,'der Experte, -n', N'专家');
INSERT INTO "StudyItems" VALUES(70,'der Faden, ^ / -', N'线');
INSERT INTO "StudyItems" VALUES(1,'der Fahrkartenautomat, -en', N'自动售票机');
INSERT INTO "StudyItems" VALUES(2,'der Fahrradhelm, -e', N'自行车安全帽');
INSERT INTO "StudyItems" VALUES(3,'der Fahrradkurier,   -e', N'骑自行车的信使');
INSERT INTO "StudyItems" VALUES(4,'der Fahrradweg, -e', N'自行车道');
INSERT INTO "StudyItems" VALUES(5,'der Fahrschein, -e', N'车票');
INSERT INTO "StudyItems" VALUES(6,'der Fakt,   -en', N'事实');
INSERT INTO "StudyItems" VALUES(7,'der Familienname, -n,   -n', N'姓');
INSERT INTO "StudyItems" VALUES(8,'der Familienstand', N'婚姻状况');
INSERT INTO "StudyItems" VALUES(9,'der Fan, -s', N'狂热者，迷');
INSERT INTO "StudyItems" VALUES(10,'der Februar (Feb.)', N'二月');
INSERT INTO "StudyItems" VALUES(11,'der Fehler, -', N'错误');
INSERT INTO "StudyItems" VALUES(12,'der Feind, -e', N'敌人');
INSERT INTO "StudyItems" VALUES(13,'der Fernseher,   -', N'电视机');
INSERT INTO "StudyItems" VALUES(14,'der Film, -e', N'电影，胶卷');
INSERT INTO "StudyItems" VALUES(15,'der Finger, -', N'手指');
INSERT INTO "StudyItems" VALUES(16,'der Fisch, -e', N'鱼');
INSERT INTO "StudyItems" VALUES(17,'der Fleischer, -', N'卖肉者');
INSERT INTO "StudyItems" VALUES(18,'der Fluch, ^e', N'咒骂');
INSERT INTO "StudyItems" VALUES(19,'der Flügel,   -', N'三角钢琴');
INSERT INTO "StudyItems" VALUES(20,'der Flughafen, ^', N'机场');
INSERT INTO "StudyItems" VALUES(21,'der Fortschritt, -e', N'进步');
INSERT INTO "StudyItems" VALUES(22,'der Fortschritt, -e', N'进步');
INSERT INTO "StudyItems" VALUES(23,'der Franzose, -n', N'法国人');
INSERT INTO "StudyItems" VALUES(24,'der Freitag, -e', N'星期五');
INSERT INTO "StudyItems" VALUES(25,'der Freund,-e', N'朋友');
INSERT INTO "StudyItems" VALUES(26,'der Friseur, -e', N'理发师');
INSERT INTO "StudyItems" VALUES(27,'der Frühling, -e', N'春季，春天');
INSERT INTO "StudyItems" VALUES(28,'der Fuchs,   ^e', N'狐狸');
INSERT INTO "StudyItems" VALUES(29,'der Fürst,   -en', N'诸侯');
INSERT INTO "StudyItems" VALUES(30,'der Fußboden,   ^', N'地面；地板');
INSERT INTO "StudyItems" VALUES(31,'der Gallenstein,   -e', N'胆结石');
INSERT INTO "StudyItems" VALUES(32,'der Garten,   ^', N'花园');
INSERT INTO "StudyItems" VALUES(33,'der Gast, ^e', N'客人');
INSERT INTO "StudyItems" VALUES(34,'der Geburtsort, -e', N'出生地点');
INSERT INTO "StudyItems" VALUES(35,'der Geburtstag, -e', N'生日');
INSERT INTO "StudyItems" VALUES(36,'der Gedanke, -n', N'思想；想法');
INSERT INTO "StudyItems" VALUES(37,'der Gegenstand,   ^e', N'物件，东西');
INSERT INTO "StudyItems" VALUES(38,'der Gehweg, -e', N'人行道');
INSERT INTO "StudyItems" VALUES(39,'der Geiz', N'吝啬，小气');
INSERT INTO "StudyItems" VALUES(40,'der Geldschein, -e', N'纸币');
INSERT INTO "StudyItems" VALUES(41,'der Geograph,   -en', N'地理学家');
INSERT INTO "StudyItems" VALUES(42,'der Geschmack', N'鉴赏力；口味');
INSERT INTO "StudyItems" VALUES(43,'der Großvater, ^', N'(外)祖父');
INSERT INTO "StudyItems" VALUES(44,'der Grund,^e', N'原因，理由');
INSERT INTO "StudyItems" VALUES(45,'der Hafen, ^', N'港口');
INSERT INTO "StudyItems" VALUES(46,'der Hals, ^e', N'颈');
INSERT INTO "StudyItems" VALUES(47,'der Hammer,   ^', N'榔头');
INSERT INTO "StudyItems" VALUES(48,'der Handschuh, -e', N'手套');
INSERT INTO "StudyItems" VALUES(49,'der Hase, -n', N'兔子');
INSERT INTO "StudyItems" VALUES(50,'der Held,   -en', N'英雄，勇士');
INSERT INTO "StudyItems" VALUES(51,'der Herbst, -e', N'秋季，秋天');
INSERT INTO "StudyItems" VALUES(52,'der Herd,   -e    .', N'炉子');
INSERT INTO "StudyItems" VALUES(53,'der Herr, -n,   -en', N'先生');
INSERT INTO "StudyItems" VALUES(54,'der Himmelstempel', N'天坛');
INSERT INTO "StudyItems" VALUES(55,'der Hintern,   -', N'臀部');
INSERT INTO "StudyItems" VALUES(56,'der Hochseefischer,   -', N'远洋渔业者');
INSERT INTO "StudyItems" VALUES(57,'der Hochzeitsmarsch, ^e', N'婚礼进行曲');
INSERT INTO "StudyItems" VALUES(58,'der Holzfäller,   -', N'伐木工');
INSERT INTO "StudyItems" VALUES(59,'der Honig', N'蜂蜜');
INSERT INTO "StudyItems" VALUES(60,'der Hörer,   -', N'听众');
INSERT INTO "StudyItems" VALUES(61,'der Humor', N'幽默');
INSERT INTO "StudyItems" VALUES(62,'der Hund, -e', N'狗');
INSERT INTO "StudyItems" VALUES(63,'der Hunger', N'饥饿');
INSERT INTO "StudyItems" VALUES(64,'der Husten', N'咳嗽');
INSERT INTO "StudyItems" VALUES(65,'der Hustensaft, ^e', N'咳嗽药水');
INSERT INTO "StudyItems" VALUES(66,'der Hut, ^e', N'帽子');
INSERT INTO "StudyItems" VALUES(67,'der Indianer, -', N'印地安人');
INSERT INTO "StudyItems" VALUES(68,'der Informatiker,   -', N'计算机工程师');
INSERT INTO "StudyItems" VALUES(69,'der Ingenieur, -e', N'工程师');
INSERT INTO "StudyItems" VALUES(70,'der Ingwer', N'姜');
INSERT INTO "StudyItems" VALUES(1,'der Inhaber, -', N'持有者');
INSERT INTO "StudyItems" VALUES(2,'der Inhalt, -e', N'内容');
INSERT INTO "StudyItems" VALUES(3,'der Inhalt, -e', N'内容');
INSERT INTO "StudyItems" VALUES(4,'der Intellektuelle, -n', N'知识分子');
INSERT INTO "StudyItems" VALUES(5,'der Intelligenztest,   -s', N'智力测验');
INSERT INTO "StudyItems" VALUES(6,'der Irrtum, ^er', N'错误');
INSERT INTO "StudyItems" VALUES(7,'der Italiener, -', N'意大利人');
INSERT INTO "StudyItems" VALUES(8,'der Januar (Jan.)', N'一月');
INSERT INTO "StudyItems" VALUES(9,'der Japaner, -', N'日本人');
INSERT INTO "StudyItems" VALUES(10,'der Jasmintee', N'茉莉花茶');
INSERT INTO "StudyItems" VALUES(11,'der Jazz', N'爵士乐');
INSERT INTO "StudyItems" VALUES(12,'der Joghurt, -s', N'酸奶');
INSERT INTO "StudyItems" VALUES(13,'der Jubel', N'欢呼；欢腾');
INSERT INTO "StudyItems" VALUES(14,'der Jugendliche, -n  (wieAdj.)', N'青少年');
INSERT INTO "StudyItems" VALUES(15,'der Juli', N'七月');
INSERT INTO "StudyItems" VALUES(16,'der Junge, -n, -n', N'男孩');
INSERT INTO "StudyItems" VALUES(17,'der Juni', N'六月');
INSERT INTO "StudyItems" VALUES(18,'der Kaffee', N'咖啡');
INSERT INTO "StudyItems" VALUES(19,'der Kaiser, -', N'皇帝');
INSERT INTO "StudyItems" VALUES(20,'der Kaiserpalast', N'故宫');
INSERT INTO "StudyItems" VALUES(21,'der Kanzler,    -', N'总理');
INSERT INTO "StudyItems" VALUES(22,'der Kapitän,   -e', N'船长');
INSERT INTO "StudyItems" VALUES(23,'der Käse', N'奶酪');
INSERT INTO "StudyItems" VALUES(24,'der Kaufmann, ...leute', N'商人');
INSERT INTO "StudyItems" VALUES(25,'der Keks,   -e', N'饼干');
INSERT INTO "StudyItems" VALUES(26,'der Kindergarten,   ^', N'幼儿园');
INSERT INTO "StudyItems" VALUES(27,'der Kindertag', N'儿童节');
INSERT INTO "StudyItems" VALUES(28,'der Kiosk, -e', N'书报亭（卖月票)');
INSERT INTO "StudyItems" VALUES(29,'der Klang,   ^e', N'音调；乐声');
INSERT INTO "StudyItems" VALUES(30,'der Klassenkamerad, -en, -en', N'(中小学)同学');
INSERT INTO "StudyItems" VALUES(31,'der Klatsch', N'流言蜚语；背后议论');
INSERT INTO "StudyItems" VALUES(32,'der Kleiderschrank,   ^e', N'衣橱');
INSERT INTO "StudyItems" VALUES(33,'der Knochen,   -', N'骨');
INSERT INTO "StudyItems" VALUES(34,'der Koch, ^e', N'厨师');
INSERT INTO "StudyItems" VALUES(35,'der Koffer, -', N'箱子');
INSERT INTO "StudyItems" VALUES(36,'der Kollege, -n, -n', N'同事');
INSERT INTO "StudyItems" VALUES(37,'der Kommilitone, -n, -n', N'大学同学');
INSERT INTO "StudyItems" VALUES(38,'der Komponist, -en', N'作曲家');
INSERT INTO "StudyItems" VALUES(39,'der König, -e', N'国王');
INSERT INTO "StudyItems" VALUES(40,'der Konsument,   -en, -en', N'消费者');
INSERT INTO "StudyItems" VALUES(41,'der Kontakt,   -e', N'联系，接触');
INSERT INTO "StudyItems" VALUES(42,'der Kontext,   -e', N'上下文');
INSERT INTO "StudyItems" VALUES(43,'der Kontinent, -e', N'大陆；大洲');
INSERT INTO "StudyItems" VALUES(44,'der Kontoauszug, ^e', N'(自动机)银行结单');
INSERT INTO "StudyItems" VALUES(45,'der Kontostand, ^e', N'帐面情况');
INSERT INTO "StudyItems" VALUES(46,'der Kontrolleur, -e', N'查票员');
INSERT INTO "StudyItems" VALUES(47,'der Koreaner, -', N'韩国人');
INSERT INTO "StudyItems" VALUES(48,'der Kranich, -e', N'鹤');
INSERT INTO "StudyItems" VALUES(49,'der Kredit,   -e', N'信贷，贷款');
INSERT INTO "StudyItems" VALUES(50,'der Krieg,   -e', N'战争');
INSERT INTO "StudyItems" VALUES(51,'der Krimi, -s', N'侦探小说');
INSERT INTO "StudyItems" VALUES(52,'der Kuchen, -', N'蛋糕');
INSERT INTO "StudyItems" VALUES(53,'der Kugelschreiber, -', N'圆珠笔');
INSERT INTO "StudyItems" VALUES(54,'der Kühler, -', N'(汽车)水箱，散热器');
INSERT INTO "StudyItems" VALUES(55,'der Kühlschrank,^e', N'冰箱');
INSERT INTO "StudyItems" VALUES(56,'der Kummer', N'苦闷；痛苦；苦恼');
INSERT INTO "StudyItems" VALUES(57,'der Kunde, -n', N'顾客');
INSERT INTO "StudyItems" VALUES(58,'der Künstler, -', N'艺术家');
INSERT INTO "StudyItems" VALUES(59,'der Laden, ^', N'店');
INSERT INTO "StudyItems" VALUES(60,'der Lamatempel', N'雍和宫');
INSERT INTO "StudyItems" VALUES(61,'der Landsmann, ...leute', N'同胞');
INSERT INTO "StudyItems" VALUES(62,'der Landweg', N'陆路');
INSERT INTO "StudyItems" VALUES(63,'der Lärm', N'噪音');
INSERT INTO "StudyItems" VALUES(64,'der Lebenslauf, ^e', N'简历');
INSERT INTO "StudyItems" VALUES(65,'der Lebensstandard, -s', N'生活水准');
INSERT INTO "StudyItems" VALUES(66,'der Lebensstil, -e', N'生活方式，生活风格');
INSERT INTO "StudyItems" VALUES(67,'der Ledergürtel, -', N'皮带');
INSERT INTO "StudyItems" VALUES(68,'der Lederschuh, -e', N'皮鞋');
INSERT INTO "StudyItems" VALUES(69,'der Lehrer, -', N'教师');
INSERT INTO "StudyItems" VALUES(70,'der Lehrertag', N'教师节');
INSERT INTO "StudyItems" VALUES(1,'der Leichtathlet, -en, -en', N'田径运动员');
INSERT INTO "StudyItems" VALUES(2,'der Liebesroman, -e', N'爱情小说');
INSERT INTO "StudyItems" VALUES(3,'der Lift, -e / -s', N'电梯');
INSERT INTO "StudyItems" VALUES(4,'der Lippenstift, -e', N'唇笔，口红');
INSERT INTO "StudyItems" VALUES(5,'der Liter', N'(一)升');
INSERT INTO "StudyItems" VALUES(6,'der Lohn, ^e', N'工资');
INSERT INTO "StudyItems" VALUES(7,'der Magen,  ^', N'胃');
INSERT INTO "StudyItems" VALUES(8,'der Magister, -', N'硕士');
INSERT INTO "StudyItems" VALUES(9,'der Mai', N'五月');
INSERT INTO "StudyItems" VALUES(10,'der Maler, -', N'画家');
INSERT INTO "StudyItems" VALUES(11,'der Mann, ^ er', N'男人；丈夫');
INSERT INTO "StudyItems" VALUES(12,'der Mantel,   ^', N'外衣，大衣');
INSERT INTO "StudyItems" VALUES(13,'der Markt, ^e', N'市场');
INSERT INTO "StudyItems" VALUES(14,'der März', N'三月');
INSERT INTO "StudyItems" VALUES(15,'der Maschinenbau', N'机械制造');
INSERT INTO "StudyItems" VALUES(16,'der Mathematiker,   -', N'数学家');
INSERT INTO "StudyItems" VALUES(17,'der Meister, -', N'乐师；师傅');
INSERT INTO "StudyItems" VALUES(18,'der Mensch, -en, -en', N'人');
INSERT INTO "StudyItems" VALUES(19,'der Minister, -', N'部长');
INSERT INTO "StudyItems" VALUES(20,'der Mitbewohner, -', N'同室(或屋)住的人');
INSERT INTO "StudyItems" VALUES(21,'der Mitbürger, -', N'同国人');
INSERT INTO "StudyItems" VALUES(22,'der Mittag, -e', N'中午');
INSERT INTO "StudyItems" VALUES(23,'der Mittwoch, -e', N'星期三');
INSERT INTO "StudyItems" VALUES(24,'der Moment, -e', N'片刻');
INSERT INTO "StudyItems" VALUES(25,'der Monat, -e', N'月，月份');
INSERT INTO "StudyItems" VALUES(26,'der Mönch, -e', N'和尚');
INSERT INTO "StudyItems" VALUES(27,'der Mond', N'月亮');
INSERT INTO "StudyItems" VALUES(28,'der Mondkalender', N'阴历');
INSERT INTO "StudyItems" VALUES(29,'der Montag, -e', N'星期一');
INSERT INTO "StudyItems" VALUES(30,'der Mord,   -e', N'谋杀');
INSERT INTO "StudyItems" VALUES(31,'der Morgen, -', N'早晨');
INSERT INTO "StudyItems" VALUES(32,'der Mund, ^er', N'嘴巴');
INSERT INTO "StudyItems" VALUES(33,'der Muskel,   -n', N'肌肉');
INSERT INTO "StudyItems" VALUES(34,'der Muttersprachler,   -', N'讲母语的人');
INSERT INTO "StudyItems" VALUES(35,'der Nachbar, -n, -n', N'邻居');
INSERT INTO "StudyItems" VALUES(36,'der Nachhilfeunterricht', N'补课');
INSERT INTO "StudyItems" VALUES(37,'der Nachmieter, -', N'后继房客');
INSERT INTO "StudyItems" VALUES(38,'der Nachmittag, -e', N'下午');
INSERT INTO "StudyItems" VALUES(39,'der Nachteil, -e', N'缺点');
INSERT INTO "StudyItems" VALUES(40,'der Nachttopf, ^e', N'便壶');
INSERT INTO "StudyItems" VALUES(41,'der Nährwert, -e', N'(热量单位)营养价值');
INSERT INTO "StudyItems" VALUES(42,'der Name,   -n, -n', N'名字');
INSERT INTO "StudyItems" VALUES(43,'der Nationalfeiertag, -e', N'国庆节');
INSERT INTO "StudyItems" VALUES(44,'der Neckar', N'内卡河');
INSERT INTO "StudyItems" VALUES(45,'der Neid', N'嫉妒；羡慕');
INSERT INTO "StudyItems" VALUES(46,'der Nordchinese, -n, -n', N'(中国)北方人');
INSERT INTO "StudyItems" VALUES(47,'der November (Nov.)', N'十一月');
INSERT INTO "StudyItems" VALUES(48,'der Oberkörper, -', N'上身');
INSERT INTO "StudyItems" VALUES(49,'der Offizier, -e', N'军官');
INSERT INTO "StudyItems" VALUES(50,'der Oktober (Okt.)', N'十月');
INSERT INTO "StudyItems" VALUES(51,'der Onkel, -', N'叔叔；舅舅；伯父');
INSERT INTO "StudyItems" VALUES(52,'der Opa, -s', N'爷爷；外公');
INSERT INTO "StudyItems" VALUES(53,'der Opiumkrieg', N'鸦片战争');
INSERT INTO "StudyItems" VALUES(54,'der Orden, -', N'勋章');
INSERT INTO "StudyItems" VALUES(55,'der Ozean,   -e', N'海洋');
INSERT INTO "StudyItems" VALUES(56,'der Palast, ^e', N'宫殿');
INSERT INTO "StudyItems" VALUES(57,'der Paprika, -(s)', N'甜椒');
INSERT INTO "StudyItems" VALUES(58,'der Papst,   ^e', N'罗马教皇');
INSERT INTO "StudyItems" VALUES(59,'der Park, -s', N'公园');
INSERT INTO "StudyItems" VALUES(60,'der Paß, -sse', N'护照');
INSERT INTO "StudyItems" VALUES(61,'der Pfeffer', N'胡椒');
INSERT INTO "StudyItems" VALUES(62,'der Pfeffer', N'胡椒');
INSERT INTO "StudyItems" VALUES(63,'der Physiker, -', N'物理学家，物理工作者');
INSERT INTO "StudyItems" VALUES(64,'der Pilz, -e', N'蘑菇');
INSERT INTO "StudyItems" VALUES(65,'der Platz des Himmlischen Friedens', N'天安门广场');
INSERT INTO "StudyItems" VALUES(66,'der Pole, -n', N'波兰人');
INSERT INTO "StudyItems" VALUES(67,'der Politiker, -', N'政治家');
INSERT INTO "StudyItems" VALUES(68,'der Postangestellte, -n', N'邮局职员');
INSERT INTO "StudyItems" VALUES(69,'der Preis, -e', N'价值');
INSERT INTO "StudyItems" VALUES(70,'der Prinz,   -en', N'王子');
INSERT INTO "StudyItems" VALUES(1,'der Professor, -en', N'教授');
INSERT INTO "StudyItems" VALUES(2,'der Profi, -s', N'职业运动员');
INSERT INTO "StudyItems" VALUES(3,'der Psychologe, -n', N'心理学家');
INSERT INTO "StudyItems" VALUES(4,'der Pudding,   -e/-s', N'布丁');
INSERT INTO "StudyItems" VALUES(5,'der Pulli, -s', N'毛衣');
INSERT INTO "StudyItems" VALUES(6,'der Pullover, -', N'毛线套衫');
INSERT INTO "StudyItems" VALUES(7,'der Puls,   -e', N'脉搏');
INSERT INTO "StudyItems" VALUES(8,'der Radler,   -', N'骑自行车者');
INSERT INTO "StudyItems" VALUES(9,'der Rang, ^e', N'等级');
INSERT INTO "StudyItems" VALUES(10,'der Regen', N'雨');
INSERT INTO "StudyItems" VALUES(11,'der Regenmantel,   ^', N'雨衣');
INSERT INTO "StudyItems" VALUES(12,'der Regenschirm, -e', N'雨伞');
INSERT INTO "StudyItems" VALUES(13,'der Reifen, -', N'轮胎');
INSERT INTO "StudyItems" VALUES(14,'der Reis', N'稻米，大米');
INSERT INTO "StudyItems" VALUES(15,'der Reiseführer, -', N'导游');
INSERT INTO "StudyItems" VALUES(16,'der Rennwagen, -', N'(比赛用)赛车');
INSERT INTO "StudyItems" VALUES(17,'der Rentner, -', N'退休者');
INSERT INTO "StudyItems" VALUES(18,'der Reporter, -', N'记者；通讯员');
INSERT INTO "StudyItems" VALUES(19,'der Rhein', N'莱茵河');
INSERT INTO "StudyItems" VALUES(20,'der Rinderbraten, -', N'烤牛肉');
INSERT INTO "StudyItems" VALUES(21,'der Rock,   ^e', N'裙子');
INSERT INTO "StudyItems" VALUES(22,'der Rohstoff,   -e', N'原料');
INSERT INTO "StudyItems" VALUES(23,'der Rücken, -', N'背');
INSERT INTO "StudyItems" VALUES(24,'der Rundfunk', N'广播');
INSERT INTO "StudyItems" VALUES(25,'der Saal, Säle', N'大厅，礼堂');
INSERT INTO "StudyItems" VALUES(26,'der Saft, ^e', N'汁，果汁');
INSERT INTO "StudyItems" VALUES(27,'der Salat, -e', N'生菜，色拉');
INSERT INTO "StudyItems" VALUES(28,'der Sammler, -', N'收藏家');
INSERT INTO "StudyItems" VALUES(29,'der Samstag, -e', N'星期六');
INSERT INTO "StudyItems" VALUES(30,'der Satz, ^e', N'句子');
INSERT INTO "StudyItems" VALUES(31,'der Schadenersatz', N'赔偿损失');
INSERT INTO "StudyItems" VALUES(32,'der Schal, -s', N'长围巾');
INSERT INTO "StudyItems" VALUES(33,'der Schalter, -', N'窗口');
INSERT INTO "StudyItems" VALUES(34,'der Schalter, -', N'窗口');
INSERT INTO "StudyItems" VALUES(35,'der Schauspieler, -', N'演员');
INSERT INTO "StudyItems" VALUES(36,'der Scheck, -s', N'支票');
INSERT INTO "StudyItems" VALUES(37,'der Scherenschnitt, -e', N'剪纸');
INSERT INTO "StudyItems" VALUES(38,'der Schläger, -', N'球拍');
INSERT INTO "StudyItems" VALUES(39,'der Schlankheitstee', N'减肥茶');
INSERT INTO "StudyItems" VALUES(40,'der Schluß, ^sse', N'结束');
INSERT INTO "StudyItems" VALUES(41,'der Schlüssel, -', N'钥匙');
INSERT INTO "StudyItems" VALUES(42,'der Schmuck', N'饰品');
INSERT INTO "StudyItems" VALUES(43,'der Schnaps, ^e', N'白酒');
INSERT INTO "StudyItems" VALUES(44,'der Schneider, -', N'裁缝');
INSERT INTO "StudyItems" VALUES(45,'der Schnelldienst, -e', N'快速服务');
INSERT INTO "StudyItems" VALUES(46,'der Schnellimbiß, ...bisse', N'快餐店');
INSERT INTO "StudyItems" VALUES(47,'der Schnupfen, -', N'流涕');
INSERT INTO "StudyItems" VALUES(48,'der Schreck, -en', N'惊恐');
INSERT INTO "StudyItems" VALUES(49,'der Schreibtisch, -e', N'写字台');
INSERT INTO "StudyItems" VALUES(50,'der Schriftsteller, -', N'作家');
INSERT INTO "StudyItems" VALUES(51,'der Schuh, -e', N'鞋子');
INSERT INTO "StudyItems" VALUES(52,'der Schüler, -', N'学生');
INSERT INTO "StudyItems" VALUES(53,'der Schulleiter, -', N'(中小学)校长');
INSERT INTO "StudyItems" VALUES(54,'der Schutt', N'瓦砾，废墟');
INSERT INTO "StudyItems" VALUES(55,'der Schwager,   ^', N'姐夫；妹夫；连襟');
INSERT INTO "StudyItems" VALUES(56,'der Schwarze, -n (wieAdj.)', N'黑人');
INSERT INTO "StudyItems" VALUES(57,'der Schwiegersohn, ^e', N'女婿');
INSERT INTO "StudyItems" VALUES(58,'der Seefahrer, -', N'船员，海员');
INSERT INTO "StudyItems" VALUES(59,'der Seetang', N'大藻叶');
INSERT INTO "StudyItems" VALUES(60,'der Seeweg', N'水路');
INSERT INTO "StudyItems" VALUES(61,'der Sekt,   -e', N'香槟酒');
INSERT INTO "StudyItems" VALUES(62,'der Selbstzahler, -', N'自费生');
INSERT INTO "StudyItems" VALUES(63,'der September (Sept.)', N'九月');
INSERT INTO "StudyItems" VALUES(64,'der Sesam', N'芝麻');
INSERT INTO "StudyItems" VALUES(65,'der Sessel,   -', N'(带扶手的)沙发椅');
INSERT INTO "StudyItems" VALUES(66,'der Sieg, -e', N'胜利');
INSERT INTO "StudyItems" VALUES(67,'der Sieger,    -', N'胜利者');
INSERT INTO "StudyItems" VALUES(68,'der Sinn, -e', N'意义');
INSERT INTO "StudyItems" VALUES(69,'der Skat', N'斯卡特(德国一种三人玩的纸牌游戏)');
INSERT INTO "StudyItems" VALUES(70,'der Sohn, ^e', N'儿子');
INSERT INTO "StudyItems" VALUES(1,'der Soldat,   -en,   -en', N'士兵，战士');
INSERT INTO "StudyItems" VALUES(2,'der Solist, -en', N'独奏者');
INSERT INTO "StudyItems" VALUES(3,'der Sommer, -', N'夏季，夏天');
INSERT INTO "StudyItems" VALUES(4,'der Sommermantel, ^', N'夏装');
INSERT INTO "StudyItems" VALUES(5,'der Sommerpalast', N'颐和园');
INSERT INTO "StudyItems" VALUES(6,'der Sonnabend, e', N'星期六');
INSERT INTO "StudyItems" VALUES(7,'der Sonntag, -e', N'星期天');
INSERT INTO "StudyItems" VALUES(8,'der Spanier, -', N'西班牙人');
INSERT INTO "StudyItems" VALUES(9,'der Spaziergang, ^e', N'散步');
INSERT INTO "StudyItems" VALUES(10,'der Spiegel, -', N'镜子');
INSERT INTO "StudyItems" VALUES(11,'der Sport', N'体育');
INSERT INTO "StudyItems" VALUES(12,'der Sportler, -', N'运动员');
INSERT INTO "StudyItems" VALUES(13,'der Sportplatz, ^e', N'操场');
INSERT INTO "StudyItems" VALUES(14,'der Sportschuh, -e', N'休闲鞋');
INSERT INTO "StudyItems" VALUES(15,'der Sportwagen, -', N'赛车型轿车');
INSERT INTO "StudyItems" VALUES(16,'der Staat, -en', N'国家');
INSERT INTO "StudyItems" VALUES(17,'der Staatsbesuch', N'国家访问');
INSERT INTO "StudyItems" VALUES(18,'der Stadtplan, ^e', N'城市地图');
INSERT INTO "StudyItems" VALUES(19,'der Standardbrief, -e', N'标准信');
INSERT INTO "StudyItems" VALUES(20,'der Standort, -e', N'所在位置');
INSERT INTO "StudyItems" VALUES(21,'der Stau, -s', N'堵车');
INSERT INTO "StudyItems" VALUES(22,'der Staubsauger, -', N'吸尘器');
INSERT INTO "StudyItems" VALUES(23,'der Stift,   -e', N'笔');
INSERT INTO "StudyItems" VALUES(24,'der Stipendiat, -en', N'奖学金生');
INSERT INTO "StudyItems" VALUES(25,'der Stoff, -e', N'料子');
INSERT INTO "StudyItems" VALUES(26,'der Strand, ^e', N'海滩，海滨');
INSERT INTO "StudyItems" VALUES(27,'der Streß', N'紧张状态');
INSERT INTO "StudyItems" VALUES(28,'der Strumpf, ^e', N'长统袜');
INSERT INTO "StudyItems" VALUES(29,'der Student, -en, -en', N'大学生');
INSERT INTO "StudyItems" VALUES(30,'der Stuhl,   ^e', N'椅子');
INSERT INTO "StudyItems" VALUES(31,'der Stundenplan, ^e', N'课程表');
INSERT INTO "StudyItems" VALUES(32,'der Supermarkt, ^e', N'超市');
INSERT INTO "StudyItems" VALUES(33,'der Tabak', N'烟草');
INSERT INTO "StudyItems" VALUES(34,'der Tagesablauf, ^e', N'日程安排');
INSERT INTO "StudyItems" VALUES(35,'der Tante-Emma-Laden,   ^', N'杂货店');
INSERT INTO "StudyItems" VALUES(36,'der Täter,   -', N'作案人');
INSERT INTO "StudyItems" VALUES(37,'der Tee', N'茶');
INSERT INTO "StudyItems" VALUES(38,'der Teich, -e', N'池塘，水池');
INSERT INTO "StudyItems" VALUES(39,'der Teilnehmer, -', N'参加者');
INSERT INTO "StudyItems" VALUES(40,'der Teller, -', N'盘子');
INSERT INTO "StudyItems" VALUES(41,'der Tempel, -', N'庙');
INSERT INTO "StudyItems" VALUES(42,'der Teppich,   -e', N'地毯');
INSERT INTO "StudyItems" VALUES(43,'der Termin,   -e', N'(规定好的)日期');
INSERT INTO "StudyItems" VALUES(44,'der Terminkalender, -', N'记事日历');
INSERT INTO "StudyItems" VALUES(45,'der Test,   -s', N'测验');
INSERT INTO "StudyItems" VALUES(46,'der Teufel,   -', N'魔鬼');
INSERT INTO "StudyItems" VALUES(47,'der Text, -e', N'课文');
INSERT INTO "StudyItems" VALUES(48,'der Thron,   -e', N'皇冠，王位，宝座');
INSERT INTO "StudyItems" VALUES(49,'der Tiananmen-Platz', N'天安门广场');
INSERT INTO "StudyItems" VALUES(50,'der Tisch,   -e', N'桌子');
INSERT INTO "StudyItems" VALUES(51,'der Titel, -', N'头衔');
INSERT INTO "StudyItems" VALUES(52,'der Topf, ^e', N'锅');
INSERT INTO "StudyItems" VALUES(53,'der Tourist, -en, -en', N'旅行者');
INSERT INTO "StudyItems" VALUES(54,'Der Traum der Roten Kammer', N'红楼梦');
INSERT INTO "StudyItems" VALUES(55,'der Traum, ^e', N'梦想');
INSERT INTO "StudyItems" VALUES(56,'der Tunnel, -', N'隧道');
INSERT INTO "StudyItems" VALUES(57,'der Turm, ^e', N'塔（楼）');
INSERT INTO "StudyItems" VALUES(58,'der Typ,  -en', N'类型');
INSERT INTO "StudyItems" VALUES(59,'der Überblick, -e', N'概况，概要');
INSERT INTO "StudyItems" VALUES(60,'der Umweltschutz', N'环境保护');
INSERT INTO "StudyItems" VALUES(61,'der Unsinn', N'胡说八道');
INSERT INTO "StudyItems" VALUES(62,'der Unterricht', N'课');
INSERT INTO "StudyItems" VALUES(63,'der Unterschied,   -e', N'区别');
INSERT INTO "StudyItems" VALUES(64,'der Vater, ^', N'父亲');
INSERT INTO "StudyItems" VALUES(65,'der Vati,   -s', N'爸爸');
INSERT INTO "StudyItems" VALUES(66,'der Verband, ^e', N'社团，协会');
INSERT INTO "StudyItems" VALUES(67,'der Verein, -e', N'协会');
INSERT INTO "StudyItems" VALUES(68,'der Verfasser, -', N'作者');
INSERT INTO "StudyItems" VALUES(69,'der Vergleich,   -e', N'比较');
INSERT INTO "StudyItems" VALUES(70,'der Verkäufer, -', N'营业员');
INSERT INTO "StudyItems" VALUES(1,'der Verrückte, -n  (wieAdj.)', N'疯子');
INSERT INTO "StudyItems" VALUES(2,'der Vertrag, ^e', N'合同；协定');
INSERT INTO "StudyItems" VALUES(3,'der Verwandte,   -n', N'亲戚');
INSERT INTO "StudyItems" VALUES(4,'der Videorecorder,   -', N'录像机');
INSERT INTO "StudyItems" VALUES(5,'der Vormittag, -e', N'上午');
INSERT INTO "StudyItems" VALUES(6,'der Vorname, -n, -n', N'名');
INSERT INTO "StudyItems" VALUES(7,'der Vorschlag, ^e', N'建议');
INSERT INTO "StudyItems" VALUES(8,'der Vorteil, -e', N'优势；优点');
INSERT INTO "StudyItems" VALUES(9,'der Wagenheber, -', N'起重器，千斤顶');
INSERT INTO "StudyItems" VALUES(10,'der Weber, -', N'纺织工');
INSERT INTO "StudyItems" VALUES(11,'der Wecker, -', N'闹钟');
INSERT INTO "StudyItems" VALUES(12,'der Wehrdienst', N'兵役');
INSERT INTO "StudyItems" VALUES(13,'der Wein, -e', N'葡萄酒');
INSERT INTO "StudyItems" VALUES(14,'der Weltmeister, -', N'世界冠军');
INSERT INTO "StudyItems" VALUES(15,'der Wert, -e', N'价值');
INSERT INTO "StudyItems" VALUES(16,'der Westsee', N'西湖');
INSERT INTO "StudyItems" VALUES(17,'der Wettkampf,   ^e', N'比赛');
INSERT INTO "StudyItems" VALUES(18,'der Wind, -e', N'风');
INSERT INTO "StudyItems" VALUES(19,'der Winter,   -', N'冬季，冬天');
INSERT INTO "StudyItems" VALUES(20,'der Wirtschaftswissenschaftler,   -', N'经济学家');
INSERT INTO "StudyItems" VALUES(21,'der Wissenschaftler, -', N'科学家');
INSERT INTO "StudyItems" VALUES(22,'der Wochentag,   -e', N'工作日');
INSERT INTO "StudyItems" VALUES(23,'der Wohlhabende, -n  (wie Adj.)', N'富裕的人');
INSERT INTO "StudyItems" VALUES(24,'der Wohlstand', N'富裕');
INSERT INTO "StudyItems" VALUES(25,'der Wolf, ^e', N'狼');
INSERT INTO "StudyItems" VALUES(26,'der Wunsch, ^e', N'愿望');
INSERT INTO "StudyItems" VALUES(27,'der Zahlungsverkehr', N'支付往来');
INSERT INTO "StudyItems" VALUES(28,'der Zahnarzt, ^e', N'牙医');
INSERT INTO "StudyItems" VALUES(29,'der Zebrastreifen, -', N'斑马线');
INSERT INTO "StudyItems" VALUES(30,'der Zeitraum, ^e', N'时间，时期');
INSERT INTO "StudyItems" VALUES(31,'der Zeittakt', N'时间频率');
INSERT INTO "StudyItems" VALUES(32,'der Zelter, -', N'露宿帐篷者');
INSERT INTO "StudyItems" VALUES(33,'der Zettel, -', N'纸条');
INSERT INTO "StudyItems" VALUES(34,'der Zins, -en', N'银行利息');
INSERT INTO "StudyItems" VALUES(35,'der Zoll, ^e', N'海关');
INSERT INTO "StudyItems" VALUES(36,'der Zoo, -s', N'动物园');
INSERT INTO "StudyItems" VALUES(37,'der Zucker', N'糖');
INSERT INTO "StudyItems" VALUES(38,'der Zuhörer, -', N'听众');
INSERT INTO "StudyItems" VALUES(39,'der Zusammenbruch,^e', N'崩溃');
INSERT INTO "StudyItems" VALUES(40,'der Zuschauer, -', N'观众');
INSERT INTO "StudyItems" VALUES(41,'der Zuschauer,   -', N'观众');
INSERT INTO "StudyItems" VALUES(42,'der Zweck,   -e', N'目的，意图');
INSERT INTO "StudyItems" VALUES(43,'der Zwerg, -e', N'矮人，侏儒');
INSERT INTO "StudyItems" VALUES(44,'der /das Meter, -', N'米，公尺');
INSERT INTO "StudyItems" VALUES(45,'der jenige (dasjenige, diejenige) Pron.', N'这一个，那一个');
INSERT INTO "StudyItems" VALUES(46,'des halb   Adv./Konj.', N'因此，所以');
INSERT INTO "StudyItems" VALUES(47,' Deutschland', N'德国');
INSERT INTO "StudyItems" VALUES(48,'die Hochschule, -n', N'大学，高校');
INSERT INTO "StudyItems" VALUES(49,'die Korrespondenzanschrift, -en', N'联系地址');
INSERT INTO "StudyItems" VALUES(50,'die Sekundarschule, -n', N'(瑞士)中学');
INSERT INTO "StudyItems" VALUES(51,'die Vorwahl, -en', N'预拨号');
INSERT INTO "StudyItems" VALUES(52,'die Abendzeitung, -en', N'晚报');
INSERT INTO "StudyItems" VALUES(53,'die Abfahrtszeit', N'发车时问');
INSERT INTO "StudyItems" VALUES(54,'die Abkürzung, -en', N'缩写');
INSERT INTO "StudyItems" VALUES(55,'die Abnutzung, -en', N'消耗，磨损');
INSERT INTO "StudyItems" VALUES(56,'die Abrechnung, -en', N'结帐');
INSERT INTO "StudyItems" VALUES(57,'die Absicht,   -en', N'打算；意图');
INSERT INTO "StudyItems" VALUES(58,'die Abteilungsleiterin, -nen', N'部门领导(女)');
INSERT INTO "StudyItems" VALUES(59,'die Abwechslung, -en', N'调节');
INSERT INTO "StudyItems" VALUES(60,'die Abwicklung, -en', N'进行');
INSERT INTO "StudyItems" VALUES(61,'die Adresse ,-n', N'地址，住址');
INSERT INTO "StudyItems" VALUES(62,'die Agrarwissenschaft', N'农学');
INSERT INTO "StudyItems" VALUES(63,'die Ahnung,-en', N'预感；，猜想');
INSERT INTO "StudyItems" VALUES(64,'die Akrobatik', N'杂技，技巧');
INSERT INTO "StudyItems" VALUES(65,'die Aktivität, -en', N'活动');
INSERT INTO "StudyItems" VALUES(66,'die Aktivität, -en', N'活动');
INSERT INTO "StudyItems" VALUES(67,'die Altstadt,   ^e', N'老城');
INSERT INTO "StudyItems" VALUES(68,'die Amerikanerin, -nen', N'美国人(女)');
INSERT INTO "StudyItems" VALUES(69,'die Ampel, -n', N'交通信号灯');
INSERT INTO "StudyItems" VALUES(70,'die Analyse, -n', N'分析');
INSERT INTO "StudyItems" VALUES(1,'die Anerkennung', N'承认；肯定；赞赏');
INSERT INTO "StudyItems" VALUES(2,'die Angel,   -n', N'钓竿，钓具');
INSERT INTO "StudyItems" VALUES(3,'die Angestellte, -n (wie Adj.)', N'职员(女)');
INSERT INTO "StudyItems" VALUES(4,'die Ankunft', N'到达');
INSERT INTO "StudyItems" VALUES(5,'die Anlage, -n', N'设施');
INSERT INTO "StudyItems" VALUES(6,'die Anrede, -n', N'称呼');
INSERT INTO "StudyItems" VALUES(7,'die Anschrift, -en', N'通讯地址');
INSERT INTO "StudyItems" VALUES(8,'die Anstalt,   -en', N'设施');
INSERT INTO "StudyItems" VALUES(9,'die Anweisung, -en', N'指令');
INSERT INTO "StudyItems" VALUES(10,'die Anzeige', N'海报，(报纸等上的)广告');
INSERT INTO "StudyItems" VALUES(11,'die Arbeit', N'工作，结束');
INSERT INTO "StudyItems" VALUES(12,'die Arbeitsbedingung, -en', N'工作条件');
INSERT INTO "StudyItems" VALUES(13,'die Arbeitserlaubnis, -se', N'工作许可证');
INSERT INTO "StudyItems" VALUES(14,'die Arbeitslosigkeit', N'失业');
INSERT INTO "StudyItems" VALUES(15,'die Architektur', N'建筑学');
INSERT INTO "StudyItems" VALUES(16,'die Armut', N'贫困');
INSERT INTO "StudyItems" VALUES(17,'die Atmosphäre, -n', N'气氛');
INSERT INTO "StudyItems" VALUES(18,'die Auflage,   -n', N'印数');
INSERT INTO "StudyItems" VALUES(19,'die Aufnahmeprüfung, -en', N'高考');
INSERT INTO "StudyItems" VALUES(20,'die Ausbildung, -en', N'教育，培养');
INSERT INTO "StudyItems" VALUES(21,'die Ausrede, -n', N'籍口，借口');
INSERT INTO "StudyItems" VALUES(22,'die Ausrüstung, -en', N'装备');
INSERT INTO "StudyItems" VALUES(23,'die Ausstellung, -en', N'展览会');
INSERT INTO "StudyItems" VALUES(24,'die Auswahl', N'选择');
INSERT INTO "StudyItems" VALUES(25,'die Auswahl', N'选择，挑选');
INSERT INTO "StudyItems" VALUES(26,'die Autobahn, -en', N'高速公路');
INSERT INTO "StudyItems" VALUES(27,'die Axt, ^e', N'斧子');
INSERT INTO "StudyItems" VALUES(28,'die Bäckerei, -en', N'面包房');
INSERT INTO "StudyItems" VALUES(29,'die Bahn, -en', N'铁路；火车');
INSERT INTO "StudyItems" VALUES(30,'die Bambussprosse, -n', N'笋头');
INSERT INTO "StudyItems" VALUES(31,'die Banane, -n', N'香蕉');
INSERT INTO "StudyItems" VALUES(32,'die Band, -s', N'乐队');
INSERT INTO "StudyItems" VALUES(33,'die Bank, -en', N'银行');
INSERT INTO "StudyItems" VALUES(34,'die Banknote, -n', N'钞票');
INSERT INTO "StudyItems" VALUES(35,'die Batterie, -n', N'电池');
INSERT INTO "StudyItems" VALUES(36,'die Bedeutung,  -en', N'意义，含义');
INSERT INTO "StudyItems" VALUES(37,'die Bedingung, -en', N'条件');
INSERT INTO "StudyItems" VALUES(38,'die Bekanntmachung, -en', N'通告，通知');
INSERT INTO "StudyItems" VALUES(39,'die Belohnung, -en', N'奖赏，酬金');
INSERT INTO "StudyItems" VALUES(40,'die Belohnung, -en', N'报酬，酬金');
INSERT INTO "StudyItems" VALUES(41,'die Berufstätigkeit, -en', N'职业工作');
INSERT INTO "StudyItems" VALUES(42,'die Besatzung,   -en', N'(在此)驻船人员；全体乘务人员，机组人员');
INSERT INTO "StudyItems" VALUES(43,'die Beschreibung,   -en', N'描绘');
INSERT INTO "StudyItems" VALUES(44,'die Beschreibung, -en', N'描绘');
INSERT INTO "StudyItems" VALUES(45,'die Besonderheit, -en', N'特殊性');
INSERT INTO "StudyItems" VALUES(46,'die Besprechung, -en', N'会谈');
INSERT INTO "StudyItems" VALUES(47,'die Bestellung, -en', N'预订；订的货');
INSERT INTO "StudyItems" VALUES(48,'die Bevölkerung,   -en', N'居民');
INSERT INTO "StudyItems" VALUES(49,'die Bewegung, -en', N'动作；运动');
INSERT INTO "StudyItems" VALUES(50,'die Bewerbung,   -en', N'谋求');
INSERT INTO "StudyItems" VALUES(51,'die Bewerbungsunterlagen   PL', N'申请材料');
INSERT INTO "StudyItems" VALUES(52,'die Beziehung, -en', N'关系');
INSERT INTO "StudyItems" VALUES(53,'die Bibliothek,   -en', N'图书馆');
INSERT INTO "StudyItems" VALUES(54,'die Biologie', N'生物学');
INSERT INTO "StudyItems" VALUES(55,'die Bluse, -n', N'女衬衫');
INSERT INTO "StudyItems" VALUES(56,'die Boulevar-Zeitung,   -en', N'(以轰动性消息为特点的)马路小报');
INSERT INTO "StudyItems" VALUES(57,'die Briefmarke, -n', N'邮票');
INSERT INTO "StudyItems" VALUES(58,'die Briefsendung, -en', N'寄信');
INSERT INTO "StudyItems" VALUES(59,'die Brieftasche, -n', N'钱包');
INSERT INTO "StudyItems" VALUES(60,'die Brille,    -n', N'眼镜');
INSERT INTO "StudyItems" VALUES(61,'die Buchdruchkerkunst', N'印刷术');
INSERT INTO "StudyItems" VALUES(62,'die Buchhandlung, -en', N'书店');
INSERT INTO "StudyItems" VALUES(63,'die Büchse, -n', N'(金属)小罐，小盒');
INSERT INTO "StudyItems" VALUES(64,'die Bude,   -n', N'木屋，售货亭');
INSERT INTO "StudyItems" VALUES(65,'die Bühne, -n', N'舞台');
INSERT INTO "StudyItems" VALUES(66,'die Bühne, -n', N'舞台');
INSERT INTO "StudyItems" VALUES(67,'die Bundesliga', N'联邦足球联赛(甲级）联合会');
INSERT INTO "StudyItems" VALUES(68,'die Bundesrepublik Deutschland', N'德意志联邦共和国');
INSERT INTO "StudyItems" VALUES(69,'die Bushaltestelle, -n', N'汽车站');
INSERT INTO "StudyItems" VALUES(70,'die Bushaltestelle, -n', N'汽车站');
INSERT INTO "StudyItems" VALUES(1,'die Butter', N'黄油。');
INSERT INTO "StudyItems" VALUES(2,'die CD, -s', N'激光唱片');
INSERT INTO "StudyItems" VALUES(3,'die Chance, -n', N'机会');
INSERT INTO "StudyItems" VALUES(4,'die Chemie', N'化学');
INSERT INTO "StudyItems" VALUES(5,'die Chemikerin, -nen', N'化学家(女)，化学工作者(女)');
INSERT INTO "StudyItems" VALUES(6,'die Chinesin, -nen', N'中国人(女)');
INSERT INTO "StudyItems" VALUES(7,'die Cola = Coca-Cola', N'(可口)可乐');
INSERT INTO "StudyItems" VALUES(8,'die Cousine, -n', N'堂姐妹；表姐妹');
INSERT INTO "StudyItems" VALUES(9,'die Creme, -s', N'润肤膏');
INSERT INTO "StudyItems" VALUES(10,'die Dame, -n', N'女士(更优雅）');
INSERT INTO "StudyItems" VALUES(11,'die Darbietung,  -en', N'表演，节目');
INSERT INTO "StudyItems" VALUES(12,'die Dichte,   -n', N'密度；比重');
INSERT INTO "StudyItems" VALUES(13,'die Diele,   -n', N'门厅  ');
INSERT INTO "StudyItems" VALUES(14,'die Dienstreise,   -n', N'出差');
INSERT INTO "StudyItems" VALUES(15,'die Dienstreise, -n', N'出差');
INSERT INTO "StudyItems" VALUES(16,'die Disco, -s', N'迪斯科');
INSERT INTO "StudyItems" VALUES(17,'die Doktorarbeit, -en', N'博士论文');
INSERT INTO "StudyItems" VALUES(18,'die Dokumentation,   -en', N'文件的汇编');
INSERT INTO "StudyItems" VALUES(19,'die Dose, -n', N'罐头');
INSERT INTO "StudyItems" VALUES(20,'die Drillinge   PL', N'三胞胎');
INSERT INTO "StudyItems" VALUES(21,'die Durchsage, -n', N'广播');
INSERT INTO "StudyItems" VALUES(22,'die ec-Karte, -n', N'磁卡');
INSERT INTO "StudyItems" VALUES(23,'die Ecke, -n', N'角落，拐角');
INSERT INTO "StudyItems" VALUES(24,'die Ehe, -n', N'婚姻');
INSERT INTO "StudyItems" VALUES(25,'die Ehefrau,   -en', N'妻子');
INSERT INTO "StudyItems" VALUES(26,'die Eigenschaft, -en', N'特征；性质');
INSERT INTO "StudyItems" VALUES(27,'die Einheit', N'统一');
INSERT INTO "StudyItems" VALUES(28,'die Einstellung,   -en', N'态度；观点；看法');
INSERT INTO "StudyItems" VALUES(29,'die Eintrittskarte, -n', N'入场券，门票');
INSERT INTO "StudyItems" VALUES(30,'die Eintrittskarte, -n', N'入场券');
INSERT INTO "StudyItems" VALUES(31,'die Einzelfahrkarte, -n', N'单程票');
INSERT INTO "StudyItems" VALUES(32,'die Einzugsermächtigung, -en', N'收款授权');
INSERT INTO "StudyItems" VALUES(33,'die Eisenstange, -n', N'(在此)金箍棒');
INSERT INTO "StudyItems" VALUES(34,'die Elektrotechnik', N'电工学');
INSERT INTO "StudyItems" VALUES(35,'die Empfehlung, -en', N'建议；推荐');
INSERT INTO "StudyItems" VALUES(36,'die Engländerin, -nen', N'英国人(女)');
INSERT INTO "StudyItems" VALUES(37,'die Enkelin, -nen', N'孙女；外孙女');
INSERT INTO "StudyItems" VALUES(38,'die Entfernung, -en', N'距离');
INSERT INTO "StudyItems" VALUES(39,'die Entschuldigung, -en', N'对不起');
INSERT INTO "StudyItems" VALUES(40,'die Erdbeere, -n', N'草莓');
INSERT INTO "StudyItems" VALUES(41,'die Erde', N'地球');
INSERT INTO "StudyItems" VALUES(42,'die Erdkunde', N'地理(学)');
INSERT INTO "StudyItems" VALUES(43,'die Erhu, -s', N'二胡');
INSERT INTO "StudyItems" VALUES(44,'die Erklärung, -en', N'说明，解释');
INSERT INTO "StudyItems" VALUES(45,'die Ernährung', N'营养；食物');
INSERT INTO "StudyItems" VALUES(46,'die Erscheinung, -en', N'现象');
INSERT INTO "StudyItems" VALUES(47,'die Etage,     -n', N'楼层');
INSERT INTO "StudyItems" VALUES(48,'die Fähigkeit,   -en', N'能力');
INSERT INTO "StudyItems" VALUES(49,'die Fahrkarte, -n', N'车票');
INSERT INTO "StudyItems" VALUES(50,'die Familie, -n', N'家庭');
INSERT INTO "StudyItems" VALUES(51,'die Farbe, -n', N'颜色');
INSERT INTO "StudyItems" VALUES(52,'die Fensterscheibe, -n', N'窗玻璃');
INSERT INTO "StudyItems" VALUES(53,'die Figur', N'体型');
INSERT INTO "StudyItems" VALUES(54,'die Filiale, -n', N'分店');
INSERT INTO "StudyItems" VALUES(55,'die Fläche,    -n', N'面积');
INSERT INTO "StudyItems" VALUES(56,'die Fläche, -n', N'面积');
INSERT INTO "StudyItems" VALUES(57,'die Flasche, -n', N'瓶子');
INSERT INTO "StudyItems" VALUES(58,'die Forelle, -n', N'鳟鱼');
INSERT INTO "StudyItems" VALUES(59,'die Form, -en', N'形式；(这里指)种类');
INSERT INTO "StudyItems" VALUES(60,'die Formulierung,   -en', N'遣词，造句，表达');
INSERT INTO "StudyItems" VALUES(61,'die Fortbildung, -en', N'进修');
INSERT INTO "StudyItems" VALUES(62,'die Frage,   -n', N'问题');
INSERT INTO "StudyItems" VALUES(63,'die Französin, -nen', N'法国人(女)、');
INSERT INTO "StudyItems" VALUES(64,'die Frau, -en', N'女人；夫人');
INSERT INTO "StudyItems" VALUES(65,'die Frechheit, -en', N'放肆，狂妄，傲漫');
INSERT INTO "StudyItems" VALUES(66,'die Freizeitbeschäftigung, -en', N'业余活动');
INSERT INTO "StudyItems" VALUES(67,'die Fremdsprache, -n', N'外语');
INSERT INTO "StudyItems" VALUES(68,'die Freundschaft, -en', N'友谊');
INSERT INTO "StudyItems" VALUES(69,'die Frisur,   -en', N'发式，发型');
INSERT INTO "StudyItems" VALUES(70,'die Frühlingsrolle, -n', N'春卷');
INSERT INTO "StudyItems" VALUES(1,'die Führungsschicht, -en', N'领导阶层');
INSERT INTO "StudyItems" VALUES(2,'die Füllung, -en', N'馅');
INSERT INTO "StudyItems" VALUES(3,'die Fünflinge    PL', N'五胞胎');
INSERT INTO "StudyItems" VALUES(4,'die Garantie, -n', N'保证；保修');
INSERT INTO "StudyItems" VALUES(5,'die Geburtstagsfeier, -n', N'生日庆祝');
INSERT INTO "StudyItems" VALUES(6,'die Geduld', N'耐心');
INSERT INTO "StudyItems" VALUES(7,'die Gefahr, -en', N'危险');
INSERT INTO "StudyItems" VALUES(8,'die Gegend, -en', N'地区');
INSERT INTO "StudyItems" VALUES(9,'die Geheimzahl, -en', N'密码');
INSERT INTO "StudyItems" VALUES(10,'die Geisteswissenschaft, -en', N'人文科学');
INSERT INTO "StudyItems" VALUES(11,'die Geldtasche, -n', N'钱包');
INSERT INTO "StudyItems" VALUES(12,'die Gemüsefrau, -en', N'卖蔬菜的妇女');
INSERT INTO "StudyItems" VALUES(13,'die Generation, -en', N'代，辈');
INSERT INTO "StudyItems" VALUES(14,'die Generation, -en', N'世代，辈');
INSERT INTO "StudyItems" VALUES(15,'die Geographie', N'地理');
INSERT INTO "StudyItems" VALUES(16,'die Geschäftszeit, -en', N'营业时问');
INSERT INTO "StudyItems" VALUES(17,'die Geschichte, -n', N'历史；故事');
INSERT INTO "StudyItems" VALUES(18,'die Geschwister PL', N'兄弟姐妹');
INSERT INTO "StudyItems" VALUES(19,'die Gesellschaft, -en', N'社会');
INSERT INTO "StudyItems" VALUES(20,'die Geste, -n', N'手势');
INSERT INTO "StudyItems" VALUES(21,'die Gewohnheit, -en', N'习惯');
INSERT INTO "StudyItems" VALUES(22,'die Glasnudel, -n', N'粉丝');
INSERT INTO "StudyItems" VALUES(23,'die Grenze,   -n', N'边境');
INSERT INTO "StudyItems" VALUES(24,'die Grenze, -n', N'边界');
INSERT INTO "StudyItems" VALUES(25,'die Grippe', N'流感');
INSERT INTO "StudyItems" VALUES(26,'die Größe', N'(身材，尺码)大小');
INSERT INTO "StudyItems" VALUES(27,'die Große Mauer', N'长城');
INSERT INTO "StudyItems" VALUES(28,'die Großeltern PL', N'(外)祖父母');
INSERT INTO "StudyItems" VALUES(29,'die Großmutter,   ^', N'(外)祖母');
INSERT INTO "StudyItems" VALUES(30,'die Grundlage, -n', N'前提');
INSERT INTO "StudyItems" VALUES(31,'die Grundschule, -n', N'小学');
INSERT INTO "StudyItems" VALUES(32,'die Gurke, -n', N'黄瓜');
INSERT INTO "StudyItems" VALUES(33,'die Hami-Melone,   -n', N'哈密瓜');
INSERT INTO "StudyItems" VALUES(34,'die Handelsstadt, ^e', N'贸易城市');
INSERT INTO "StudyItems" VALUES(35,'die Hauptstadt, ^e', N'首都');
INSERT INTO "StudyItems" VALUES(36,'die Hausarbeit', N'家庭作业(论文)');
INSERT INTO "StudyItems" VALUES(37,'die Hausaufgabe, -n', N'家庭作业');
INSERT INTO "StudyItems" VALUES(38,'die Hausfrau, -en', N'家庭妇女');
INSERT INTO "StudyItems" VALUES(39,'die Haut,   ^e', N'皮肤');
INSERT INTO "StudyItems" VALUES(40,'die Heimatstadt, ^e', N'家乡');
INSERT INTO "StudyItems" VALUES(41,'die Heizung, -en', N'暖气设备');
INSERT INTO "StudyItems" VALUES(42,'die Hierarchie,   -n', N'社会等级');
INSERT INTO "StudyItems" VALUES(43,'die Hilfe, -n', N'帮助');
INSERT INTO "StudyItems" VALUES(44,'die Hochleistung', N'高效率');
INSERT INTO "StudyItems" VALUES(45,'die Hochzeitsfeier, -n', N'婚礼庆典');
INSERT INTO "StudyItems" VALUES(46,'die Höflichkeit, -en', N'客气，礼貌');
INSERT INTO "StudyItems" VALUES(47,'die Hörerin, -nen', N'听众(女)');
INSERT INTO "StudyItems" VALUES(48,'die Hose,   -n', N'裤子');
INSERT INTO "StudyItems" VALUES(49,'die Informatik', N'信息学；计算机科学');
INSERT INTO "StudyItems" VALUES(50,'die Information, -en', N'消息，报道');
INSERT INTO "StudyItems" VALUES(51,'die Insel,   -n', N'岛屿');
INSERT INTO "StudyItems" VALUES(52,'die Insel,   -n', N'岛');
INSERT INTO "StudyItems" VALUES(53,'die Jacke, -n', N'茄克衫');
INSERT INTO "StudyItems" VALUES(54,'die Jahreszahl,   -en', N'年份');
INSERT INTO "StudyItems" VALUES(55,'die Jahreszeit, -en', N'季节');
INSERT INTO "StudyItems" VALUES(56,'die Jahrhundertwende, -n', N'世纪之交');
INSERT INTO "StudyItems" VALUES(57,'die Japanerin, -nen', N'日本人(女)');
INSERT INTO "StudyItems" VALUES(58,'die Jeans PL', N'牛仔衣裤');
INSERT INTO "StudyItems" VALUES(59,'die Kaffeemaschine,   -n', N'煮咖啡机');
INSERT INTO "StudyItems" VALUES(60,'die Kaki,   -s', N'柿子');
INSERT INTO "StudyItems" VALUES(61,'die Kalligraphie, -n', N'书法');
INSERT INTO "StudyItems" VALUES(62,'die Kalorie, -n', N'卡，卡路里');
INSERT INTO "StudyItems" VALUES(63,'die Kanone, -n', N'炮');
INSERT INTO "StudyItems" VALUES(64,'die Kantine, -n', N'（教师/工厂的）食堂');
INSERT INTO "StudyItems" VALUES(65,'die Karriere, -n', N'职业生涯');
INSERT INTO "StudyItems" VALUES(66,'die Karriereaussicht,   -en', N'普升机会');
INSERT INTO "StudyItems" VALUES(67,'die Kartoffel, -n', N'土豆');
INSERT INTO "StudyItems" VALUES(68,'die Kasse, -n', N'帐台，付款处');
INSERT INTO "StudyItems" VALUES(69,'die Kassette, -n', N'盒式磁带');
INSERT INTO "StudyItems" VALUES(70,'die Kaution, -en', N'租房保证金');
INSERT INTO "StudyItems" VALUES(1,'die Kenntnis, -se', N'知识');
INSERT INTO "StudyItems" VALUES(2,'die Kernenergie, -n', N'核能');
INSERT INTO "StudyItems" VALUES(3,'die Kindergärtnerin, -nen', N'幼儿园老师(女)');
INSERT INTO "StudyItems" VALUES(4,'die Kinderpflegerin, -nen', N'托儿所保育员');
INSERT INTO "StudyItems" VALUES(5,'die Kirche, -n', N'教堂');
INSERT INTO "StudyItems" VALUES(6,'die Klasse, -n', N'班级');
INSERT INTO "StudyItems" VALUES(7,'die Kleidung', N'服装');
INSERT INTO "StudyItems" VALUES(8,'die Klimaanlage, -n', N'空调');
INSERT INTO "StudyItems" VALUES(9,'die Kneipe, -n', N'小酒馆，酒吧');
INSERT INTO "StudyItems" VALUES(10,'die Knoblauchzehe, -n', N'蒜瓣');
INSERT INTO "StudyItems" VALUES(11,'die Kohle', N'煤炭');
INSERT INTO "StudyItems" VALUES(12,'die Kommerzialisierung, -en', N'商业化');
INSERT INTO "StudyItems" VALUES(13,'die Kommunikation, -en', N'交际，交流');
INSERT INTO "StudyItems" VALUES(14,'die Konferenz, -en', N'会议');
INSERT INTO "StudyItems" VALUES(15,'die Konferenz, -en', N'会议');
INSERT INTO "StudyItems" VALUES(16,'die Königin, -nen', N'女王，王后');
INSERT INTO "StudyItems" VALUES(17,'die Königin, -nen', N'女王');
INSERT INTO "StudyItems" VALUES(18,'die Kopiermaschine, -n', N'复印机');
INSERT INTO "StudyItems" VALUES(19,'die Koreanerin, -nen', N'韩国人(女)');
INSERT INTO "StudyItems" VALUES(20,'die Körperhaltung, -en', N'体态，身体动作');
INSERT INTO "StudyItems" VALUES(21,'die Körperhaltung, -en', N'体态，身体动作');
INSERT INTO "StudyItems" VALUES(22,'die Kosmetika Pl.', N'化妆品');
INSERT INTO "StudyItems" VALUES(23,'die Kraft, ^e', N'力量');
INSERT INTO "StudyItems" VALUES(24,'die Krankenschwester, -n', N'护士');
INSERT INTO "StudyItems" VALUES(25,'die Kreditkarte, -n', N'信用卡');
INSERT INTO "StudyItems" VALUES(26,'die Kreuzung, -en', N'十字路口');
INSERT INTO "StudyItems" VALUES(27,'die Kriminalität', N'犯罪，犯罪率');
INSERT INTO "StudyItems" VALUES(28,'die Küche,    -n', N'厨房');
INSERT INTO "StudyItems" VALUES(29,'die Kulturrevolution', N'文化大革命');
INSERT INTO "StudyItems" VALUES(30,'die Kunst, ^e', N'艺术');
INSERT INTO "StudyItems" VALUES(31,'die Lackarbeit, -en', N'漆器');
INSERT INTO "StudyItems" VALUES(32,'die Lampe,   -n', N'灯');
INSERT INTO "StudyItems" VALUES(33,'die Laterne, -n', N'灯笼');
INSERT INTO "StudyItems" VALUES(34,'die Lebensmittel   PL', N'食品；日用品（一般指食品）');
INSERT INTO "StudyItems" VALUES(35,'die Lehre,   -n', N'学徒的学习期');
INSERT INTO "StudyItems" VALUES(36,'die Lehrerin, -nen', N'教师(女)');
INSERT INTO "StudyItems" VALUES(37,'die Lehrkraft,   ^e', N'师资');
INSERT INTO "StudyItems" VALUES(38,'die Leiche, -n', N'尸体');
INSERT INTO "StudyItems" VALUES(39,'die Leine,   -n', N'(牵狗的)皮带');
INSERT INTO "StudyItems" VALUES(40,'die Leistung, -en', N'成绩');
INSERT INTO "StudyItems" VALUES(41,'die Lektion, -en', N'课，单元');
INSERT INTO "StudyItems" VALUES(42,'die Lernmethode, -n', N'学习方法');
INSERT INTO "StudyItems" VALUES(43,'die Leselampe, -n', N'书写台灯');
INSERT INTO "StudyItems" VALUES(44,'die Lesestrategie,   -n', N'阅读的策略');
INSERT INTO "StudyItems" VALUES(45,'die Leute PL', N'人');
INSERT INTO "StudyItems" VALUES(46,'die Liebe', N'爱');
INSERT INTO "StudyItems" VALUES(47,'die Lieblingsperson,   -en', N'最喜欢的人');
INSERT INTO "StudyItems" VALUES(48,'die Lieblingssache,   -n', N'最喜欢的物');
INSERT INTO "StudyItems" VALUES(49,'die Lieblingsspeise, -n', N'最喜欢吃的菜');
INSERT INTO "StudyItems" VALUES(50,'die Linie, -n', N'线路');
INSERT INTO "StudyItems" VALUES(51,'die Lokalisation', N'确定……位置');
INSERT INTO "StudyItems" VALUES(52,'die Lokalzeitung,   -en', N'地方报纸');
INSERT INTO "StudyItems" VALUES(53,'die Luftpost', N'航空邮件');
INSERT INTO "StudyItems" VALUES(54,'die Lunge,   -n', N'肺');
INSERT INTO "StudyItems" VALUES(55,'die Lungenentzündung, -en', N'肺炎');
INSERT INTO "StudyItems" VALUES(56,'die Lust', N'兴趣');
INSERT INTO "StudyItems" VALUES(57,'die Malerei', N'画，图画');
INSERT INTO "StudyItems" VALUES(58,'die Mango,   -s', N'芒果');
INSERT INTO "StudyItems" VALUES(59,'die Mannschaft, -en', N'运动队');
INSERT INTO "StudyItems" VALUES(60,'die Marke, -n', N'票证，票');
INSERT INTO "StudyItems" VALUES(61,'die Marmelade, -n', N'果酱');
INSERT INTO "StudyItems" VALUES(62,'die Masern PL', N'麻疹');
INSERT INTO "StudyItems" VALUES(63,'die Maske, -n', N'面具');
INSERT INTO "StudyItems" VALUES(64,'die Mathematik', N'数学');
INSERT INTO "StudyItems" VALUES(65,'die Medizin', N'医学，药');
INSERT INTO "StudyItems" VALUES(66,'die Menge, -n', N'数量');
INSERT INTO "StudyItems" VALUES(67,'die Mengenangabe, -n', N'计量词');
INSERT INTO "StudyItems" VALUES(68,'die Mengeneinheit, -en', N'量词');
INSERT INTO "StudyItems" VALUES(69,'die Mensa, ...sen', N'大学食堂');
INSERT INTO "StudyItems" VALUES(70,'die Messe, -n', N'博览会');
INSERT INTO "StudyItems" VALUES(1,'die Methode, -n', N'方法');
INSERT INTO "StudyItems" VALUES(2,'die Mikrowelle, -n', N'微波炉');
INSERT INTO "StudyItems" VALUES(3,'die Milch', N'牛奶');
INSERT INTO "StudyItems" VALUES(4,'die Milliarde, -n', N'十亿');
INSERT INTO "StudyItems" VALUES(5,'die Million, -en', N'百万');
INSERT INTO "StudyItems" VALUES(6,'die Mimik', N'脸部表情');
INSERT INTO "StudyItems" VALUES(7,'die Minggräber   PL', N'十三陵');
INSERT INTO "StudyItems" VALUES(8,'die Minute, -n', N'分');
INSERT INTO "StudyItems" VALUES(9,'die Mitternacht', N'午夜');
INSERT INTO "StudyItems" VALUES(10,'die Möhre, -n', N'胡萝卜');
INSERT INTO "StudyItems" VALUES(11,'die Mosel', N'摩泽尔河');
INSERT INTO "StudyItems" VALUES(12,'die Münze, -n', N'硬币');
INSERT INTO "StudyItems" VALUES(13,'die Musik', N'音乐');
INSERT INTO "StudyItems" VALUES(14,'die Musikwissenschaftlerin, -nen', N'音乐学家(女)');
INSERT INTO "StudyItems" VALUES(15,'die Mutter, ^', N'母亲');
INSERT INTO "StudyItems" VALUES(16,'die Muttersprache, -n', N'母语');
INSERT INTO "StudyItems" VALUES(17,'die Nachricht,   -en', N'消息；新闻');
INSERT INTO "StudyItems" VALUES(18,'die Nachspeise, -n', N'饭后甜食');
INSERT INTO "StudyItems" VALUES(19,'die Nacht, ^e', N'夜晚');
INSERT INTO "StudyItems" VALUES(20,'die Nadel, -n', N'针');
INSERT INTO "StudyItems" VALUES(21,'die Nähe', N'附近，邻近');
INSERT INTO "StudyItems" VALUES(22,'die Nahrungsmittel PL', N'食品');
INSERT INTO "StudyItems" VALUES(23,'die Nase,    -n', N'鼻子');
INSERT INTO "StudyItems" VALUES(24,'die Nationalität, -en', N'国籍');
INSERT INTO "StudyItems" VALUES(25,'die Nationalmannschaft, -en', N'国家队');
INSERT INTO "StudyItems" VALUES(26,'die Naturwissenschaft, -en', N'自然科学');
INSERT INTO "StudyItems" VALUES(27,'die Nebenkosten = NK         PL', N'附加(额外)费用');
INSERT INTO "StudyItems" VALUES(28,'die Nocturne,   -s', N'夜曲');
INSERT INTO "StudyItems" VALUES(29,'die Not, ^e', N'困境，困难');
INSERT INTO "StudyItems" VALUES(30,'die Nudel, -n', N'面条；通心面');
INSERT INTO "StudyItems" VALUES(31,'die Öffnungszeit, -en', N'开放时间');
INSERT INTO "StudyItems" VALUES(32,'die Oma, -s', N'奶奶；外婆');
INSERT INTO "StudyItems" VALUES(33,'die Oper, -n', N'歌剧院；歌剧');
INSERT INTO "StudyItems" VALUES(34,'die Orange, -n', N'橙子');
INSERT INTO "StudyItems" VALUES(35,'die Ordinalzahl, -en', N'序数词');
INSERT INTO "StudyItems" VALUES(36,'die Ordnung, -en', N'秩序，整洁');
INSERT INTO "StudyItems" VALUES(37,'die Ostsee', N'波罗的海');
INSERT INTO "StudyItems" VALUES(38,'die Packung, -en', N'一包');
INSERT INTO "StudyItems" VALUES(39,'die Pädagogik', N'教育学');
INSERT INTO "StudyItems" VALUES(40,'die Paketkarte,   -n', N'包裹单');
INSERT INTO "StudyItems" VALUES(41,'die Party, -s', N'聚会');
INSERT INTO "StudyItems" VALUES(42,'die Passantin, -nen', N'行人(女)');
INSERT INTO "StudyItems" VALUES(43,'die Pause, -n', N'休息');
INSERT INTO "StudyItems" VALUES(44,'die Person, -en', N'人，个人');
INSERT INTO "StudyItems" VALUES(45,'die Pfanne,   -n', N'平底锅');
INSERT INTO "StudyItems" VALUES(46,'die Pflanze, -n', N'植物');
INSERT INTO "StudyItems" VALUES(47,'die Pflicht,  -en', N'义务');
INSERT INTO "StudyItems" VALUES(48,'die Philosophie', N'哲学');
INSERT INTO "StudyItems" VALUES(49,'die Physik', N'物理');
INSERT INTO "StudyItems" VALUES(50,'die Pizzeria, ...rien', N'意大利馅饼店');
INSERT INTO "StudyItems" VALUES(51,'die Pommes frites  PL', N'(炸)土豆条');
INSERT INTO "StudyItems" VALUES(52,'die Popmusik', N'流行音乐');
INSERT INTO "StudyItems" VALUES(53,'die Portion,   -en', N'一份，一客');
INSERT INTO "StudyItems" VALUES(54,'die Position,   -en', N'地位');
INSERT INTO "StudyItems" VALUES(55,'die Post', N'邮局，邮件');
INSERT INTO "StudyItems" VALUES(56,'die Postkarte, -n', N'明信片');
INSERT INTO "StudyItems" VALUES(57,'die Postleitzahl (PLZ), -en', N'邮码，邮编');
INSERT INTO "StudyItems" VALUES(58,'die Prämie,   -n', N'奖金，奖赏');
INSERT INTO "StudyItems" VALUES(59,'die Praxis,   ...xen', N'诊所');
INSERT INTO "StudyItems" VALUES(60,'die Preisliste, -n', N'价目表');
INSERT INTO "StudyItems" VALUES(61,'die Presse', N'新闻界；出版界');
INSERT INTO "StudyItems" VALUES(62,'die Prinzessin, -nen', N'公主');
INSERT INTO "StudyItems" VALUES(63,'die Probe, -n', N'试演；排练');
INSERT INTO "StudyItems" VALUES(64,'die Prognose,   -n', N'诊断；预测');
INSERT INTO "StudyItems" VALUES(65,'die Promotion, -en', N'攻读博士学位');
INSERT INTO "StudyItems" VALUES(66,'die Provinz, -en', N'省');
INSERT INTO "StudyItems" VALUES(67,'die Prüfung, -en', N'考试');
INSERT INTO "StudyItems" VALUES(68,'die Psychologie', N'心理学');
INSERT INTO "StudyItems" VALUES(69,'die Qualität, -en', N'质量');
INSERT INTO "StudyItems" VALUES(70,'die Quelle, -n', N'来源');
INSERT INTO "StudyItems" VALUES(1,'die Querstraße, -n', N'横马路');
INSERT INTO "StudyItems" VALUES(2,'die Ratte,   -n', N'耗子');
INSERT INTO "StudyItems" VALUES(3,'Die Räuber vom Liangshanmoor', N'水浒');
INSERT INTO "StudyItems" VALUES(4,'die Realität, -en', N'现实');
INSERT INTO "StudyItems" VALUES(5,'die Rechnung, -en', N'帐单');
INSERT INTO "StudyItems" VALUES(6,'die Redakteurin, -nen', N'编辑(女)');
INSERT INTO "StudyItems" VALUES(7,'die Redaktion,   -en', N'编辑部');
INSERT INTO "StudyItems" VALUES(8,'die Redewendung,   -en', N'惯用语');
INSERT INTO "StudyItems" VALUES(9,'die Regierung,   -en', N'政府');
INSERT INTO "StudyItems" VALUES(10,'die Region, -en', N'地方；地区');
INSERT INTO "StudyItems" VALUES(11,'Die Reise nach Westen', N'西游记');
INSERT INTO "StudyItems" VALUES(12,'die Reisebegleitung, -en', N'旅行陪伴方式');
INSERT INTO "StudyItems" VALUES(13,'die Reklamation, -en    .', N'投诉，申诉');
INSERT INTO "StudyItems" VALUES(14,'die Religion, -en', N'宗教');
INSERT INTO "StudyItems" VALUES(15,'die Reparatur, -en', N'修理处');
INSERT INTO "StudyItems" VALUES(16,'die Reportage,   -n', N'通讯；新闻报道');
INSERT INTO "StudyItems" VALUES(17,'die Republik, -en', N'共和国');
INSERT INTO "StudyItems" VALUES(18,'die Richtung,   -en', N'方向');
INSERT INTO "StudyItems" VALUES(19,'die Rolle, -n', N'角色');
INSERT INTO "StudyItems" VALUES(20,'die Röntgenstrahlen PL', N'伦琴线');
INSERT INTO "StudyItems" VALUES(21,'die Rübe,   -n', N'罗卜');
INSERT INTO "StudyItems" VALUES(22,'die Rücksicht', N'顾虑；考虑');
INSERT INTO "StudyItems" VALUES(23,'die Rücksicht, -en', N'考虑，顾及');
INSERT INTO "StudyItems" VALUES(24,'die Sache,   -n', N'东西，衣服');
INSERT INTO "StudyItems" VALUES(25,'die Säge,   -n', N'锯子');
INSERT INTO "StudyItems" VALUES(26,'die Sahne', N'奶油；鲜奶');
INSERT INTO "StudyItems" VALUES(27,'die Salatsoße,   -n', N'色拉酱');
INSERT INTO "StudyItems" VALUES(28,'die Sängerin, -nen', N'歌唱家(女)');
INSERT INTO "StudyItems" VALUES(29,'die S-Bahn, -en', N'轻轨火车');
INSERT INTO "StudyItems" VALUES(30,'die S-Bahnstation, -en', N'轻轨车站');
INSERT INTO "StudyItems" VALUES(31,'die Scheibe, -n', N'片');
INSERT INTO "StudyItems" VALUES(32,'die Schlange, -n', N'蛇');
INSERT INTO "StudyItems" VALUES(33,'die Schokolade', N'巧克力');
INSERT INTO "StudyItems" VALUES(34,'die Schulbildung, -en', N'学校教育');
INSERT INTO "StudyItems" VALUES(35,'die Schulnote, -n', N'在学校的成绩');
INSERT INTO "StudyItems" VALUES(36,'die Schulter, -n', N'肩');
INSERT INTO "StudyItems" VALUES(37,'die Schwäche, -n', N'缺点，弱点');
INSERT INTO "StudyItems" VALUES(38,'die Schwangerschaft,   -en', N'怀孕');
INSERT INTO "StudyItems" VALUES(39,'die Schwester, -n', N'姐妹');
INSERT INTO "StudyItems" VALUES(40,'die Schwiegertochter,   ^.', N'媳妇');
INSERT INTO "StudyItems" VALUES(41,'die Schwierigkeit, -en', N'困难');
INSERT INTO "StudyItems" VALUES(42,'die Schwimmerin, -nen', N'游泳运动员(女)');
INSERT INTO "StudyItems" VALUES(43,'die Sehenswürdigkeit, -en', N'名胜古迹');
INSERT INTO "StudyItems" VALUES(44,'die Sekretärin, -nen', N'秘书(女)');
INSERT INTO "StudyItems" VALUES(45,'die Sekunde, -n', N'秒');
INSERT INTO "StudyItems" VALUES(46,'die Selbständigkeit', N'独立');
INSERT INTO "StudyItems" VALUES(47,'die Sendung,   -en', N'广播；广播节目');
INSERT INTO "StudyItems" VALUES(48,'die Sendung, -en', N'广播');
INSERT INTO "StudyItems" VALUES(49,'die Servierin, -nen', N'服务员(女)');
INSERT INTO "StudyItems" VALUES(50,'die Sicherheit, -en', N'保障');
INSERT INTO "StudyItems" VALUES(51,'die Silvesternacht, ^e', N'12月31日之夜');
INSERT INTO "StudyItems" VALUES(52,'die Sinfonie,, -n', N'交响乐');
INSERT INTO "StudyItems" VALUES(53,'die Sinologie', N'汉学');
INSERT INTO "StudyItems" VALUES(54,'die Sitte, -n', N'风俗习惯');
INSERT INTO "StudyItems" VALUES(55,'die Socke, -n', N'短袜');
INSERT INTO "StudyItems" VALUES(56,'die Softwareentwicklung,   -en', N'软件开发');
INSERT INTO "StudyItems" VALUES(57,'die Sojabohnensprosse,   -n', N'豆芽');
INSERT INTO "StudyItems" VALUES(58,'die Sojasoße', N'酱油');
INSERT INTO "StudyItems" VALUES(59,'die Solarzelle, -n', N'太阳电池');
INSERT INTO "StudyItems" VALUES(60,'die Sorte, -n', N'种类');
INSERT INTO "StudyItems" VALUES(61,'die Soße, -n', N'酱汁');
INSERT INTO "StudyItems" VALUES(62,'die Sowjetunion', N'苏联');
INSERT INTO "StudyItems" VALUES(63,'die Sozialwissenschaft, -en', N'社会科学');
INSERT INTO "StudyItems" VALUES(64,'die Soziologie', N'社会学');
INSERT INTO "StudyItems" VALUES(65,'die Spaghetti  PL', N'细长的通心面条');
INSERT INTO "StudyItems" VALUES(66,'die Spannung, -en', N'紧张');
INSERT INTO "StudyItems" VALUES(67,'die Sparkasse, -n', N'储蓄银行');
INSERT INTO "StudyItems" VALUES(68,'die Sparsamkeit', N'节俭，节约');
INSERT INTO "StudyItems" VALUES(69,'die Speisekarte, -n', N'菜单');
INSERT INTO "StudyItems" VALUES(70,'die Sportart, -en', N'体育运动项目');
INSERT INTO "StudyItems" VALUES(1,'die Sporthalle, -n', N'体育馆');
INSERT INTO "StudyItems" VALUES(2,'die Sportlerin, -nen', N'运动员(女)');
INSERT INTO "StudyItems" VALUES(3,'die Sprache,-n', N'语言');
INSERT INTO "StudyItems" VALUES(4,'die Sprechstunde, -n', N'门诊时间；答疑时间');
INSERT INTO "StudyItems" VALUES(5,'die Staatsangehörigkeit, -en', N'国籍');
INSERT INTO "StudyItems" VALUES(6,'die Stadt, ^e', N'城市');
INSERT INTO "StudyItems" VALUES(7,'die Stelle, -n', N'职位');
INSERT INTO "StudyItems" VALUES(8,'die Stellenanzeige, -n', N'招聘启示');
INSERT INTO "StudyItems" VALUES(9,'die Stereoanlage,   -n', N'立体声音响');
INSERT INTO "StudyItems" VALUES(10,'die Stimmung, -en', N'心情，情绪');
INSERT INTO "StudyItems" VALUES(11,'die Strafe, -n', N'罚款');
INSERT INTO "StudyItems" VALUES(12,'die Straße, -n', N'大街，路');
INSERT INTO "StudyItems" VALUES(13,'die Streifenkarte, -n', N'联票');
INSERT INTO "StudyItems" VALUES(14,'die Studentin -nen', N'大学生(女)');
INSERT INTO "StudyItems" VALUES(15,'die Studie,   -n', N'研究');
INSERT INTO "StudyItems" VALUES(16,'die Studiengebühr,   -en', N'学费');
INSERT INTO "StudyItems" VALUES(17,'die Suche', N'寻找  ');
INSERT INTO "StudyItems" VALUES(18,'die Suppe, -n', N'汤');
INSERT INTO "StudyItems" VALUES(19,'die Süßigkeit, -en', N'甜食');
INSERT INTO "StudyItems" VALUES(20,'die Symbolik', N'象征的语言；手法');
INSERT INTO "StudyItems" VALUES(21,'die Tabelle, -n', N'表格');
INSERT INTO "StudyItems" VALUES(22,'die Tablette, -n', N'药片');
INSERT INTO "StudyItems" VALUES(23,'die Tafel, -n', N'黑板');
INSERT INTO "StudyItems" VALUES(24,'die Tafel, -n', N'块');
INSERT INTO "StudyItems" VALUES(25,'die Tagesmutter, ^', N'保姆');
INSERT INTO "StudyItems" VALUES(26,'die Tageszeit, -en', N'白天(某一段)时间');
INSERT INTO "StudyItems" VALUES(27,'die Tageszeitung, -en', N'日报');
INSERT INTO "StudyItems" VALUES(28,'die Taktik, -en', N'战术，策略');
INSERT INTO "StudyItems" VALUES(29,'die Tante, -n', N'阿姨；姑姑；伯母');
INSERT INTO "StudyItems" VALUES(30,'die Tasche, -n', N'包');
INSERT INTO "StudyItems" VALUES(31,'die Tasse, -n', N'杯子');
INSERT INTO "StudyItems" VALUES(32,'die Technologie,   -n', N'工艺');
INSERT INTO "StudyItems" VALUES(33,'die Teilnahmegebühr, -en', N'(参加的)费用');
INSERT INTO "StudyItems" VALUES(34,'die Telefonkarte, -n', N'电话磁卡');
INSERT INTO "StudyItems" VALUES(35,'die Telefonnummer, -n', N'电话号码');
INSERT INTO "StudyItems" VALUES(36,'die Tendenz,   -en', N'趋势');
INSERT INTO "StudyItems" VALUES(37,'die Tennisspielerin, -nen', N'网球运动员(女)');
INSERT INTO "StudyItems" VALUES(38,'die Theke,   -n', N'(酒馆柜台式)桌');
INSERT INTO "StudyItems" VALUES(39,'die Theorie, -n', N'理论');
INSERT INTO "StudyItems" VALUES(40,'die Tischdecke,-n', N'桌布');
INSERT INTO "StudyItems" VALUES(41,'die Tochter, ^', N'女儿');
INSERT INTO "StudyItems" VALUES(42,'die Tomate, -n', N'西红柿');
INSERT INTO "StudyItems" VALUES(43,'die Tonarmee', N'兵马俑');
INSERT INTO "StudyItems" VALUES(44,'die Torte, -n', N'圆蛋糕');
INSERT INTO "StudyItems" VALUES(45,'die Tropfen   PL', N'滴剂');
INSERT INTO "StudyItems" VALUES(46,'die Tür, -en', N'门');
INSERT INTO "StudyItems" VALUES(47,'die Turnerin, -nen', N'体操运动员(女)');
INSERT INTO "StudyItems" VALUES(48,'die U-Bahnstation, -en', N'地铁车站');
INSERT INTO "StudyItems" VALUES(49,'die Überraschung, -en', N'惊异');
INSERT INTO "StudyItems" VALUES(50,'die Überschrift, -en', N'标题');
INSERT INTO "StudyItems" VALUES(51,'die Überweisung, -en', N'汇，汇兑');
INSERT INTO "StudyItems" VALUES(52,'die Übung, -en', N'练习');
INSERT INTO "StudyItems" VALUES(53,'die Uhr, -en', N'钟；手表');
INSERT INTO "StudyItems" VALUES(54,'die Uhrzeit, -en', N'钟点');
INSERT INTO "StudyItems" VALUES(55,'die Uhrzeitangabe, -n', N'钟点时间状语');
INSERT INTO "StudyItems" VALUES(56,'die Umfrage,   -n', N'问卷调查');
INSERT INTO "StudyItems" VALUES(57,'die Umgebung,   -en', N'环境');
INSERT INTO "StudyItems" VALUES(58,'die Umgebung, -en', N'近郊');
INSERT INTO "StudyItems" VALUES(59,'die Umwelt', N'环境');
INSERT INTO "StudyItems" VALUES(60,'die Unterhaltung,-en', N'娱乐');
INSERT INTO "StudyItems" VALUES(61,'die Unterhaltung,-en', N'娱乐');
INSERT INTO "StudyItems" VALUES(62,'die Unterkunft,   ^e', N'住宿');
INSERT INTO "StudyItems" VALUES(63,'die Untermiete, -n', N'转租');
INSERT INTO "StudyItems" VALUES(64,'die Unterwäsche', N'内衣');
INSERT INTO "StudyItems" VALUES(65,'die Urgroßeltern   PL', N'曾祖父母；曾外祖父母');
INSERT INTO "StudyItems" VALUES(66,'die Ursache, -n', N'原因');
INSERT INTO "StudyItems" VALUES(67,'die USA', N'美国');
INSERT INTO "StudyItems" VALUES(68,'die Utopie,   -n', N'理想社会；幻想');
INSERT INTO "StudyItems" VALUES(69,'die VCD,^-s', N'激光影碟片');
INSERT INTO "StudyItems" VALUES(70,'die Verabredung, -en', N'约会');
INSERT INTO "StudyItems" VALUES(1,'die Veranstaltung,   -en', N'活动；举行');
INSERT INTO "StudyItems" VALUES(2,'die Verantwortung, -en', N'责任');
INSERT INTO "StudyItems" VALUES(3,'die Verbotene Stadt', N'紫禁城');
INSERT INTO "StudyItems" VALUES(4,'die Vergangenheit, -en', N'过去');
INSERT INTO "StudyItems" VALUES(5,'die Verletzung, -en', N'受伤');
INSERT INTO "StudyItems" VALUES(6,'die Verpflegung', N'伙食');
INSERT INTO "StudyItems" VALUES(7,'die Verspätung, -en', N'迟到，误点');
INSERT INTO "StudyItems" VALUES(8,'die Verstopfung, -en', N'便秘');
INSERT INTO "StudyItems" VALUES(9,'die Verzeihung, -en', N'抱歉');
INSERT INTO "StudyItems" VALUES(10,'die Violine, -n', N'小提琴');
INSERT INTO "StudyItems" VALUES(11,'die Vision, -en', N'幻想');
INSERT INTO "StudyItems" VALUES(12,'die Volksrepublik China', N'中华人民共和国');
INSERT INTO "StudyItems" VALUES(13,'die Voraussetzung,   -en', N'先决条件');
INSERT INTO "StudyItems" VALUES(14,'die Vorführung,  -en', N'演出');
INSERT INTO "StudyItems" VALUES(15,'die Vorlesung, -en', N'讲座');
INSERT INTO "StudyItems" VALUES(16,'die Vorspeise, -n', N'餐前小吃');
INSERT INTO "StudyItems" VALUES(17,'die Waffe, -n', N'武器');
INSERT INTO "StudyItems" VALUES(18,'die Wahrheit', N'真话，实话');
INSERT INTO "StudyItems" VALUES(19,'die Waise, -n', N'孤儿');
INSERT INTO "StudyItems" VALUES(20,'die Walnuß,   ^sse', N'核桃');
INSERT INTO "StudyItems" VALUES(21,'die Wand, ^e', N'墙');
INSERT INTO "StudyItems" VALUES(22,'die Wäsche', N'衣物（待洗的）');
INSERT INTO "StudyItems" VALUES(23,'die Waschmaschine,   -n', N'洗衣机');
INSERT INTO "StudyItems" VALUES(24,'die Wassermelone, -n', N'西瓜');
INSERT INTO "StudyItems" VALUES(25,'die Weihnachten PL', N'圣诞节');
INSERT INTO "StudyItems" VALUES(26,'die Weile', N'一会儿');
INSERT INTO "StudyItems" VALUES(27,'die Weimarer Republik', N'魏玛共和国');
INSERT INTO "StudyItems" VALUES(28,'die Weise, -n', N'方式，方法');
INSERT INTO "StudyItems" VALUES(29,'die Weiterbildung, -en', N'深造');
INSERT INTO "StudyItems" VALUES(30,'die Welt', N'世界');
INSERT INTO "StudyItems" VALUES(31,'die Weltmeisterschaft, -en', N'世界冠军赛(地位)');
INSERT INTO "StudyItems" VALUES(32,'die Werbung, -en', N'广告');
INSERT INTO "StudyItems" VALUES(33,'die Wettervorhersage, -n', N'天气预报');
INSERT INTO "StudyItems" VALUES(34,'die Wiedervereinigung, -en', N'再统一');
INSERT INTO "StudyItems" VALUES(35,'die Wiese, -n', N'草坪');
INSERT INTO "StudyItems" VALUES(36,'die Winterferien  PL', N'寒假');
INSERT INTO "StudyItems" VALUES(37,'die Wirtschaftswissenschaft', N'经济学');
INSERT INTO "StudyItems" VALUES(38,'die Wissenschaft,   -en', N'科学');
INSERT INTO "StudyItems" VALUES(39,'die Witwe, -n', N'寡妇');
INSERT INTO "StudyItems" VALUES(40,'die Wohnform, -en', N'居住形式');
INSERT INTO "StudyItems" VALUES(41,'die Wohngemeinschaft, -en = WG', N'合租房');
INSERT INTO "StudyItems" VALUES(42,'die Wolke, -n', N'云');
INSERT INTO "StudyItems" VALUES(43,'die Wurst, ^e', N'香肠');
INSERT INTO "StudyItems" VALUES(44,'die Zahl, -en', N'数字');
INSERT INTO "StudyItems" VALUES(45,'die Zahnschmerzen   Pl.', N'牙疼');
INSERT INTO "StudyItems" VALUES(46,'die Zeit', N'时间');
INSERT INTO "StudyItems" VALUES(47,'die Zeitangabe, -n', N'时间状语');
INSERT INTO "StudyItems" VALUES(48,'die Zeitdauer', N'持续时间');
INSERT INTO "StudyItems" VALUES(49,'die Zeitmaschine, -n', N'时光机器');
INSERT INTO "StudyItems" VALUES(50,'die Zeitung, -en', N'报纸');
INSERT INTO "StudyItems" VALUES(51,'die Zeitungsanzeige,   -n', N'报纸广告');
INSERT INTO "StudyItems" VALUES(52,'die Zentrale, -n', N'中心；总部');
INSERT INTO "StudyItems" VALUES(53,'die Zigarette, -n', N'香烟');
INSERT INTO "StudyItems" VALUES(54,'die Zimmerdecke, -n', N'天花板');
INSERT INTO "StudyItems" VALUES(55,'die Zimmereinrichtung, -en', N'房间的布置，装饰');
INSERT INTO "StudyItems" VALUES(56,'die Zollbeamtin, -nen', N'海关官员(女)');
INSERT INTO "StudyItems" VALUES(57,'die Zone, -n', N'区域');
INSERT INTO "StudyItems" VALUES(58,'die Zone, -n', N'区域');
INSERT INTO "StudyItems" VALUES(59,'die Zukunft', N'将来');
INSERT INTO "StudyItems" VALUES(60,'die Zulassung, -en', N'入学通知书');
INSERT INTO "StudyItems" VALUES(61,'die Zutat,   -en', N'辅料；配料');
INSERT INTO "StudyItems" VALUES(62,'die Zutat, -en', N'配料，调料');
INSERT INTO "StudyItems" VALUES(63,'die Zwiebel, -n', N'洋葱');
INSERT INTO "StudyItems" VALUES(64,'die Zwillinge  PL', N'双胞胎');
INSERT INTO "StudyItems" VALUES(65,'die Zwischenprüfung, -en', N'期中考试');

